### ISSUE TITLE
Wrong output on `EMU128`

### ISSUE THREAD

**Issue by kleisauke** [google/highway#1081]
Given this example function:
```cpp
void Test() {
  auto a = Zero(di16);
  auto b = Zero(di16);

#if HWY_ARCH_X86 || HWY_ARCH_WASM || HWY_TARGET == HWY_EMU128
  /* Only one accumulator is used on x86 and Wasm.
   */
  const auto initial = Iota(di32, 1);
#else
  const auto initial = InterleaveLower(Iota(di32, 1), Zero(di32));
#endif

  auto sum0 = initial;
  auto sum1 = initial; /* unused on x86 and Wasm */

  sum0 = ReorderWidenMulAccumulate(di32, a, b, sum0, /* byref */ sum1);
  sum0 = RearrangeToOddPlusEven(sum0, sum1);

  Print(di32, "sum0", sum0, 0, Lanes(di32));
}
```

Outputs:
```
------------------------ AVX2
i32x8 sum0 [0+ ->]:
  1,2,3,4,5,6,7,8,
------------------------ SSE4
i32x4 sum0 [0+ ->]:
  1,2,3,4,
------------------------ SSSE3
i32x4 sum0 [0+ ->]:
  1,2,3,4,
------------------------ EMU128
i32x4 sum0 [0+ ->]:
  2,4,6,8,
```

Intializing `sum1` to a vector with zero in all lanes seems to fix this on `EMU128`. For example:
```diff
@@ -11,7 +11,11 @@ void Test() {
 #endif
 
   auto sum0 = initial;
+#if HWY_TARGET == HWY_EMU128
+  auto sum1 = Zero(di32);
+#else
   auto sum1 = initial; /* unused on x86 and Wasm */
+#endif
 
   sum0 = ReorderWidenMulAccumulate(di32, a, b, sum0, /* byref */ sum1);
   sum0 = RearrangeToOddPlusEven(sum0, sum1);
```

Tested on commit b203a6dd65c298b5a6ec29a830dbdf4c7f903358.

<details>
  <summary>Minimal reproducible example</summary>
  
```cpp
// Compile with:
// clang++ -O3 -DHWY_TARGET_INCLUDE=\"$(realpath test-highway.cpp)\" test-highway.cpp `pkg-config libhwy --cflags --libs`

#include <cstdint>
#include <iostream>

#include <hwy/base.h>

#include <hwy/foreach_target.h> // IWYU pragma: keep

// Must come after foreach_target.h to avoid redefinition errors.
#include <hwy/highway.h>
#include <hwy/print-inl.h>

HWY_BEFORE_NAMESPACE();
namespace hwy {
namespace HWY_NAMESPACE {

using namespace hwy::HWY_NAMESPACE;

using DI32 = ScalableTag<int32_t>;
using DI16 = ScalableTag<int16_t>;

constexpr DI16 di16;
constexpr DI32 di32;

void Test() {
  auto a = Zero(di16);
  auto b = Zero(di16);

#if HWY_ARCH_X86 || HWY_ARCH_WASM || HWY_TARGET == HWY_EMU128
  /* Only one accumulator is used on x86 and Wasm.
   */
  const auto initial = Iota(di32, 1);
#else
  const auto initial = InterleaveLower(Iota(di32, 1), Zero(di32));
#endif

  auto sum0 = initial;
  auto sum1 = initial; /* unused on x86 and Wasm */

  sum0 = ReorderWidenMulAccumulate(di32, a, b, sum0, /* byref */ sum1);
  sum0 = RearrangeToOddPlusEven(sum0, sum1);

  Print(di32, "sum0", sum0, 0, Lanes(di32));
}

void RunTest() {
  printf("------------------------ %s\n", TargetName(HWY_TARGET));
  Test();
}

// NOLINTNEXTLINE(google-readability-namespace-comments)
} // namespace HWY_NAMESPACE
} // namespace hwy
HWY_AFTER_NAMESPACE();

#if HWY_ONCE
namespace hwy {
HWY_EXPORT(RunTest);

void Run() {
  for (int64_t target : SupportedAndGeneratedTargets()) {
    SetSupportedTargetsForTest(target);
    HWY_DYNAMIC_DISPATCH(RunTest)();
  }
  SetSupportedTargetsForTest(0); // Reset the mask afterwards.
}

} // namespace hwy

int main(int /*argc*/, char ** /*argv*/) {
  hwy::Run();
  return 0;
}
#endif // HWY_ONCE
```
</details>

**Comment by jan-wassenberg** [comment]
Here we go :)
I have previously also wondered why we have the different initialization for the two accumulators, but unfortunately didn't say anything yet. It seems like the usual thing is to zero-init, and we are trying to fold a 'free addition' into the series of operations. Is that right?

Let's remember the invariant, before and after ReorderWidenMulAccumulate, is that `SumOfLanes(d, Add(sum0, sum1))` is the desired result. If we skip the ReorderWidenMulAccumulate (which is what your a=b=0 does), and start out with sum0=sum1=initial, then we are counting initial twice instead of the desired single 'free addition' of zero (result of Reorder.. of zero) plus initial. This is what happens with emu128 and I think it is within its rights to do so.

What I haven't understood is why we would ever want to assign anything but zero to sum1? If we're already willing to look at the implementation and understand that x86 ignores sum1, why not just move any nonzero input into sum0 on all platforms? If helpful, we could document that the initial value of sum1 must be zero (because it might be ignored) and sum0 can be nonzero if you want to increase the final SumOfLanes result by `SumOfLanes(d, initial_sum0)`.

Would that work for you? Or is it your concern that RearrangeToOddPlusEven is not fulfilling its guarantee? We could also repeat the sum1=0 initialization requirement there.

**Comment by kleisauke** [comment]
> It seems like the usual thing is to zero-init, and we are trying to fold a 'free addition' into the series of operations. Is that right?

Indeed, I avoided an `Add()` instruction here by initializing the sum with the addition that will occur after `RearrangeToOddPlusEven()`.

> What I haven't understood is why we would ever want to assign anything but zero to sum1? If we're already willing to look at the implementation and understand that x86 ignores sum1, why not just move any nonzero input into sum0 on all platforms? If helpful, we could document that the initial value of sum1 must be zero (because it might be ignored) and sum0 can be nonzero if you want to increase the final SumOfLanes result by `SumOfLanes(d, initial_sum0)`.

Ah, this example is a bit weird because it initializes `sum1` with `Iota()`, which is only safe on x86 and Wasm (since it uses one accumulator there). I initialized it with `Set()` in my previous implementation, but I noticed that this is _not_ safe on SVE either, see for example this gist:
https://gist.github.com/kleisauke/6246190d8b98b2bbede8a41037efaa39

I'll close this issue, commit https://github.com/kleisauke/libvips/commit/25e7ae05d376e19b7f307d7cb19f74b9593847ed ensures that `sum1` is zero-initialized on all targets.

> Would that work for you? Or is it your concern that RearrangeToOddPlusEven is not fulfilling its guarantee? We could also repeat the sum1=0 initialization requirement there.

Feel free to document the zero-initialization requirement for `ReorderWidenMulAccumulate()` and/or `RearrangeToOddPlusEven()`.  :+1:
