### ISSUE TITLE
How can i enable AVX instructions by passing compiler flags without -march=xxx?

### ISSUE THREAD

**Issue by Panhaolin2001** [google/highway#1082]
hi~
I want to compile my code without using -march=xxx, instead of just using -mxxx(like -msse3 -mavx ... ).
If i compile my code using this commond: g++ -O2 -std=c++2a -mavx  xxx.cpp, this can not enable AVX instructions. And the same situation to AVX2. So, how can i enable AVX or AVX2 instructions by passing compiler flags without -march=xxx?
Thanks!

**Comment by jan-wassenberg** [comment]
Hi, this is possible, it just requires a rather long list of -m flags. I'm curious why you want to avoid -march?

[Here is how](https://gcc.godbolt.org/z/qKTjPGaos).

The reason is that we group many CPU flags into targets, and if any of them is missing, we do not generate AVX2 code. This is to reduce the number of targets and thus compilation time and binary size.
