### ISSUE TITLE
Visual Studio Run-Time Check Failure

### ISSUE THREAD

**Issue by dlemstra** [google/highway#11]
I am using this project together with the jpeg-xl library and this now fails at the following spot:

![afbeelding](https://user-images.githubusercontent.com/10426229/103154825-8f524000-479a-11eb-9f00-4ca73c87ab0e.png)

Using the same block as the __clang__ compiler seems to resolve the issue. Maybe the check should be swapped and changed to this:

```C
template <size_t N, HWY_IF_LE128(float, N)>
HWY_API Vec128<float, N> Undefined(Simd<float, N> /* tag */) {
#ifdef __GNUC__
  __m128 raw;
  return Vec128<float, N>{raw};
#else
  return Vec128<float, N>{_mm_undefined_ps()};
#endif
}
```

**Comment by jan-wassenberg** [comment]
Thank you for reporting this! The preferred approach (undefined*) was undocumented for msvc but it turns out to work. Thus we can remove the `#if` entirely. That change will go in shortly, then we'll need to uprev the Highway submodule in jxl. Until then, would disabling the runtime checks in the compiler options help?

**Comment by dlemstra** [comment]
The @ImageMagick project uses a copy of the source code of this project and I applied the suggested patch for now.

**Comment by jan-wassenberg** [comment]
@dlemstra 
OK :) FYI other targets (avx2 etc) are also affected, but 9958d40 is now in and fixes them.

**Comment by jan-wassenberg** [comment]
FYI: have added an MSVC build to our testing infrastructure :)

**Comment by dlemstra** [comment]
Thanks for the changes will update the copy inside the ImageMagick repository at a later moment.
