### ISSUE TITLE
riscv64/clang: error: use of undeclared identifier '__riscv_vsetvlmax_e8mf8'

### ISSUE THREAD

**Issue by malaterre** [google/highway#1156]
Seems like there has been some kind of name change on riscv64:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=1.0.4%7Egit20230223.a24a3f7-1&stamp=1677229708&raw=0

```
/usr/bin/clang++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety-analysis -Wundefined-func-template -fno-cxx-exceptions -fno-slp-vectorize -fno-vectorize -fdiagnostics-show-option -fcolor-diagnostics -Wc++2a-extensions -fmath-errno -fno-exceptions -march=rv64gcv1p0 -menable-experimental-extensions -Werror -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c '/<<PKGBUILDDIR>>/hwy/per_target.cc'
In file included from /<<PKGBUILDDIR>>/hwy/per_target.cc:21:
In file included from /<<PKGBUILDDIR>>/hwy/highway.h:384:
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvlmax_e8mf8'
HWY_RVV_FOREACH(HWY_RVV_LANES, Lanes, setvlmax_e, _ALL_VIRT)
                ^
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvl_e8mf8'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvlmax_e8mf4'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvl_e8mf4'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvlmax_e8mf2'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvl_e8mf2'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvlmax_e8m1'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvl_e8m1'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvlmax_e8m2'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vsetvl_e8m2'
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:430:17: error: use of undeclared identifier '__riscv_vlenb'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by jan-wassenberg** [comment]
Yes, clang has recently switched to requiring the prefix. Not great to have another incompatible change so soon after RVV's recent mask policy change.

Unfortunately it's not very easy to handle both with/without prefix because there are 172 occurrences. Would you mind wrapping `__riscv_v##OP` (plus direct uses of `__riscv_*`) in a HWY_RVV_OP macro? Or perhaps we could add HWY_RVV to HWY_BROKEN_TARGETS if the compiler isn't new enough?

**Comment by eopXD** [comment]
Hi,
Sorry that I missed this thread. For the upgrade for the RVV intrinsics, you may refer to the compatible header here [0] for the mapping to the new v0.11 intrinsics.

@jan-wassenberg feel free to loop me into any issues of RVV intrinsics upgrade, I will be more than happy to help.

[0] https://github.com/riscv-non-isa/rvv-intrinsic-doc/tree/master/auto-generated/rvv-v0p10-compatible-headers

**Comment by eopXD** [comment]
Based on my understanding, GCC 13 will support what is now tagged as v0.11.

**Comment by jan-wassenberg** [comment]
@eopXD thanks for reaching out. We are good now for current clang. The open question is how to deal with older clang. Because we have changed our code to use the new intrinsics, the older compiler does not know those intrinsics.

I think the proposed HWY_RVV_OP macro could bridge this difference. But an open question is (@malaterre ): do we even want to support RVV on older clang, or should we simply mark it as available only on recent enough compilers?

**Comment by eopXD** [comment]
We have the compatible header shipped in our downstream compiler to allow code using v0.10 intrinsics to still work. I chatted with Alex (@asb) about including the header into upstream LLVM, we got to a conclusion that its the users freedom to do so but as the intrinsics will evolve (since its not ratified yet) the upstream compiler should care less for these legacy code and have the users upgrade their intrinsics.

I don't know if we need have a page listing out availabilities of RVV intrinsics in LLVM. Maybe Alex can help answer the question here.

**Comment by eopXD** [comment]
Yes you are right, the compatible header can not be back-ported to older compiler.

**Comment by jan-wassenberg** [comment]
Got it. Intrinsics 0.11 include the policy+prefix changes that Highway has been updated to match.

So I think we'll continue to assume a new enough clang or gcc, with no changes to our RVV implementation required.
But we will update the compiler requirements, marking RVV as available only if GCC 13+ (thanks @eopXD for this info) or Clang 16 (the first release after these recent changes).

Then it seems we can close this, but feel free to reopen if you'd like to discuss.

**Comment by jan-wassenberg** [comment]
Thanks! It appears this change has just now been made to the intrinsics doc:
https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/216/files

It was already in clang and hopefully GCC will follow soon, so great that you reported the bug. Might be good to add the above link as context.
