### ISSUE TITLE
Should the HWY_SSE2 target be added?

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1162]
While most x86 CPU's manufactured in the last 10 years have at least SSSE3/SSE4.1/SSE4.2 support, adding the HWY_SSE2 target would allow older x86 CPU's that have SSE2 support but don't have SSSE3/SSE4.1/SSE4.2 support to take advantage of the SSE/SSE2 operations that are implemented in hwy/ops/x86_128-inl.h.

The biggest issue that would be there with the HWY_SSE2 target is that SSE2 lacks an instruction for the TableLookupBytes operation that is there on most of the other SIMD instruction sets that support 128-bit or larger vectors.

Here is how TableLookupLanes could be implemented for SSE2:
```
template <typename T, size_t N, typename TI, size_t NI>
HWY_API Vec128<TI, NI> TableLookupBytes(const Vec128<T, N> bytes,
                                        const Vec128<TI, NI> from) {
#if HWY_COMPILER_GCC_ACTUAL && HWY_HAS_BUILTIN(__builtin_shuffle)
  typedef uint8_t GccU8RawVect __attribute__((__vector_size__(16)));
  return Vec128<TI, NI>{(detail::Raw128<TI>::type)
    __builtin_shuffle((GccU8RawVect)bytes.raw, (GccU8RawVect)from.raw)};
#else
  const DFromV<decltype(from)> d;
  const Repartition<uint8_t, decltype(d)> du8;
  const Full128<uint8_t> du8_full;

  const DFromV<decltype(bytes)> d_bytes;
  const Repartition<uint8_t, decltype(d_bytes)> du8_bytes;

  alignas(16) uint8_t result_bytes[16];
  alignas(16) uint8_t u8_bytes[16];
  alignas(16) uint8_t from_bytes[16];
  
  Store(Vec128<uint8_t>{BitCast(du8_bytes, bytes).raw}, du8_full, u8_bytes);
  Store(Vec128<uint8_t>{BitCast(du8, from).raw}, du8_full, from_bytes);

  for(int i = 0; i < 16; i++)
    result_bytes[i] = u8_bytes[from_bytes[i] & 15];

  return BitCast(d, Load(du8, result_bytes));
#endif
}
```

The addition of the HWY_SSE2 target would also allow all of the 64-bit x86 CPU's to be targeted without having to enable the HWY_SCALAR or HWY_EMU128 targets as all of the 64-bit x86 CPU's have at least SSE2 support.

**Comment by jan-wassenberg** [comment]
Thanks for raising this. We've indeed had some requests first for S-SSE3 (done) and also SSE2, because there are still a few percent of CPUs in the Steam hardware survey (already skewed towards gaming machines) lacking SSE4.

That looks about as good as we can do for TableLookupBytes; TableLookupBytesOr0 would also require checking from_bytes[i] & 0x80 and zeroing.

Then there are also _mm_{abs, alignr, mulhrs} to emulate. I believe that's the full list.
Would you, or someone else, be willing to send a pull request implementing those? After that we can continue to support SSE2, there is space left in the target bit values for it.
