### ISSUE TITLE
Example usage for the sorting

### ISSUE THREAD

**Issue by toshiyukinakata** [google/highway#1282]
Hello, I am more of a c programmer than a c++ programmer.
I'm very much interested in evaluating the vqsort functions to see how
they can fit into what I am trying to do..
However, there doesn't seem to be any examples of the usage of vqsort.
I notice that the operator overload in Sorter() 
so do I call Sorter(type specific parameters) in namespace hwy?

**Comment by jan-wassenberg** [comment]
Hi @toshiyukinakata , yes, that is right, the preferred interface is calling one of the operator() overloads in vqsort.h.
There is an example of how to use it in bench_sort.cc but this has some C++ abstraction layer in between: the actual call to the sorter is within algo-inl.h.

This was because the sorter class allocates some memory, so we made the sorter object thread-local. We are now able to avoid the allocation at least on x86, so this is less important now.

Note that the operator() does dynamic dispatch, basically calling through a function pointer, to ensure we use the best available instructions on your CPU. This does add some overhead especially for small arrays - vqsort is currently good for >10K items, though we could (and intend to) improve performance for small arrays.

Hope this helps + happy Easter (I am currently traveling with limited email access) :)

**Comment by toshiyukinakata** [comment]
Hi @jan-wassenberg Thank you very much I'll go and take a look. 
I am also looking forward to the performance improvement for smaller arrays..
Best

**Comment by jan-wassenberg** [comment]
You're very welcome :) I am curious to hear whether vqsort is useful to you. And please feel free to follow up with any further questions.

**Comment by jan-wassenberg** [comment]
Closing, please feel free to reopen if you'd like to continue the discussion.
