### ISSUE TITLE
clang compiler error on Travis OSX build 

### ISSUE THREAD

**Issue by boxerab** [google/highway#135]
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Here is the error:

```
 error: no template named 'ShiftRight'; did you mean 'hwy::N_SSE4::ShiftRight'?
                                        auto y = ShiftRight<2>((g+g) + b + r);
                                                 ^~~~~~~~~~
                                                 hwy::N_SSE4::ShiftRight
```
and here is the code:

```
const HWY_FULL(int32_t) d;
for(auto j = begin; j < begin + chunkSize; j += Lanes(d))
{
	auto r = Load(d,chan0+j);
	auto g = Load(d,chan1+j);
	auto b = Load(d,chan2+j);
	auto y = ShiftRight<2>((g+g) + b + r);
	auto u = b-g;
	auto v = r-g;
	Store(y,d,chan0+j);
	Store(u,d,chan1+j);
	Store(v,d,chan2+j);
}
```

NOTE: builds fine on Github Actions with latest Windows, Ubuntu and OSX VMs.

**Comment by jan-wassenberg** [comment]
Yes, this is an unfortunate language limitation. I think clang is correct to reject this.
The issue is that ShiftRight is a template, so different ADL rules apply. Non-template functions are found in namespace hwy::HWY_NAMESPACE because their arguments are classes also defined in that namespace. We have been working around this by using hwy::HWY_NAMESPACE:: ShiftRight because templates are relatively rare.

However, on targets such as RVV, where vectors are builtin types instead of wrapper classes defined by Highway, that will no longer be enough - ADL will only work for functions with hwy::Simd<> arguments (eg Set), not vector-only arguments (eg MulAdd).

If you don't care about RiscV and POWER you can continue to use the per-function using decl, but if so, I see two alternatives:
- Put using namespace hwy::HWY_NAMESPACE inside your project::HWY_NAMESPACE
- Your SIMD code resides in hwy::HWY_NAMESPACE (downside: project-specific constants/functions would then need project:: qualifiers)

Does anyone see another way?

**Comment by boxerab** [comment]
`using namespace hwy::HWY_NAMESPACE;`  fixed the compile error. Thanks!
