### ISSUE TITLE
Add testing for OpenPOWER (ppc64le)

### ISSUE THREAD

**Issue by madscientist159** [google/highway#1351]
First of all, thank you for ensuring this project supports the `ppc64le` architecture.  To assist with this effort, Raptor would be willing to provide free access to a build / test VM on a POWER9 host, or CI/CD via its public Gitlab instance.

Would this be something you are interested in utilizing?

**Comment by jan-wassenberg** [comment]
Thanks for reaching out! Our internal CI unfortunately cannot call out to anything external. Currently we are only running ppc tests manually before a release. It would be nice to add ppc testing to the Github actions here, so we see any failures  sooner.
Do you have any experience running qemu ([command line](https://github.com/google/highway/blob/master/run_tests.sh#L58)) via Github actions? Should work, right?

**Comment by madscientist159** [comment]
Unfortunately I have very limited epxerience with Github-specific tools, we use Gitlab internally.

If I provided access to a POWER9 VPS would you be able to integrate it with Github for CI/CD, or is that a non-starter?  I guarantee the VPS will be orders of magnitude faster than trying to emulate with `qemu`... :wink:

**Comment by jan-wassenberg** [comment]
I understand :)
Am not very familiar either with Github CI, integrating with VPS is beyond my current skills.
But @malaterre has suggested an action that could automatically run qemu - yes it's slower, but our tests are pretty quick and it has about 5 minutes of runway, so should be fine. Thanks for the suggestion, I've added it to TODO.

**Comment by madscientist159** [comment]
Fair enough.

We could set up a mirrored check on actual hardware on this side using our Gitlab instance.  What's the easiest way to run the ppc64 test suite from a command line?

**Comment by johnplatts** [comment]
> Fair enough.
> 
> We could set up a mirrored check on actual hardware on this side using our Gitlab instance, which would at least catch any issues that sneak through so they can be reported. What's the easiest way to run the ppc64 test suite from a command line?

The Highway tests can be run using the `ctest -j` command.

To compile only the HWY_PPC9 target, pass the `-DCTEST_CXX_FLAGS='-mcpu=power9 -DHWY_DISABLED_TARGETS=6918232715082858496'` option to the cmake command line.

There is a compiler bug in GCC 12 and later on PowerPC as the vsldoi instruction is sometimes incorrectly optimized out when optimizations are enabled, and details about this GCC bug can be found at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109069.

The HWY_PPC9 target should be compiled with GCC 11 due to the compiler bugs that are there in GCC 12.

There is also a compiler bug in Clang 16.0.0 and earlier (which actually turned out to be a bug in the LLVM DAGCombiner) that causes the a shuffle of a vector created from zero-extended extracted element to generate incorrect results on big-endian targets (including big-endian PowerPC), and details about that bug can be found at https://github.com/llvm/llvm-project/issues/61315. This vector shuffle bug has been fixed in Clang 16.0.1 and later.
