### ISSUE TITLE
Question: is it possible to simulate SSE2 only arch on AVX2 cpu ?

### ISSUE THREAD

**Issue by boxerab** [google/highway#144]
I am getting some test failures on Github actions, but all tests pass on my local machine.
My theory is that the Github VM may not have AVX2 support. Is there a way of forcing hwy
to use SSE2 instead of AVX2 ? Thanks!

**Comment by jan-wassenberg** [comment]
If a machine lacks AVX2, HWY_DYNAMIC_DISPATCH will not call into avx2 code. But maybe there is some behavior change if the vector length differs?

If you want to force either SSE4 (if available) or else scalar, you can `#define HWY_DISABLED_TARGETS (HWY_AVX2|HWY_AVX3)`. You could also call DisableTargets() at runtime.

**Comment by boxerab** [comment]
@jan-wassenberg , thanks. I think there is still a bug in `NearestInt`.

I have another issue: in debug build on my local machine, all unit tests pass, but in release mode, I get failures. And these are the unit tests that use `NearestInt`.  Any ideas on what would cause optimized builds to fail?

**Comment by boxerab** [comment]
It looks like the issue is how nan is handled. Here is output from one image,
where the first number is the input float, the second number is the result from using
`lrintf` and the third number is result from highway (with AVX2 )

```
-nan -1007394521 -1007394522
-nan -1011700221 -1011700220
-nan -1035442436 -1035442430
-nan -1007139980 -1007139979
-nan -1034464159 -1034464165
-nan -1005758366 -1005758365
-nan -1011952119 -1011952121
-nan -1033875925 -1033875937
-nan -1006175551 -1006175552
-nan -1011869590 -1011869589
-nan -1035098213 -1035098202
-nan -1006119993 -1006119994
-nan -1011858328 -1011858327
-nan -1035732256 -1035732245
-nan -1006681260 -1006681261
-nan -1033342105 -1033342099
-nan -1008146547 -1008146546
-nan -1011664160 -1011664161
-nan -1031662008 -1031662011
-nan -1009279894 -1009279893
-nan -1011523861 -1011523862
-nan -1030204790 -1030204792
```

**Comment by boxerab** [comment]
```
auto y = va_r*r + va_g*g;
```

gives a different result from

```
auto y = va_r*r;
y +=  + va_g*g;
```

The second calculation matches the C++ calculation.

**Comment by boxerab** [comment]
So, my conclusion is that vanilla C++ code compiled inside HWY method gives different results from vanilla C++ code
compiled outside of HWY method..

**Comment by jan-wassenberg** [comment]
Depending on optimization flags, the compiler may perform unsafe, non-IEEE compliant transformations.
Do you have -ffast-math enabled? I'd recommend against that.

>  that vanilla C++ code compiled inside HWY method gives different results from vanilla C++ code
compiled outside of HWY method..

This could be due to FMA - compilers may replace a*b+c with FMA (depending on fp-contract/similar flags). That might even be a good thing, though it will change results by 1E-5 or so. Presumably the results would match if you compiled everything with -ffp-contract=fast ?

**Comment by boxerab** [comment]
Thanks. I don't have -ffast-math enabled.
So, are you saying that the compiler settings for HWY method will differe from settings for non-HWY ?

**Comment by jan-wassenberg** [comment]
Yes, that is necessarily the case - on GCC and Clang, you cannot emit SIMD code without -mavx2 etc. (or the target-specific attributes used here). Given we also specify -mfma, I believe the compiler is within its rights to contract some muls.

This seems to be one platform difference we cannot abstract away - SSE4 and AVX2 are going to return different results because the former does not support FMA. Does that make sense?

**Comment by boxerab** [comment]
Thanks. I may just disable SSE4 in that case.

But, let's just take AVX2 for now. I am hoping that I can get the same outputs for
both AVX2 and scalar, so that the output is uniform across different CPUs.

Also, even in AVX2 case, I still need to run scalar on last part of a buffer sometimes depending
on the number of threads in the system, as I break up the buffer into chunks, one chunk per thread,
and there can be some leftover bytes.

**Comment by boxerab** [comment]
@jan-wassenberg thanks, I think I understand the issue now. I will have to think about the best strategy for my project.
