### ISSUE TITLE
contrib/sorter and highway ABI

### ISSUE THREAD

**Issue by malaterre** [google/highway#1446]
It seems the ABI has changed in hwy_contrib, here is what I see on my side:

* https://salsa.debian.org/debian-phototools-team/highway/-/commit/ab9281c79e06471c1e99eeacc53a00dce9f77667

Could someone please confirm the hwy_contrib git/master is no longer ABI compatible with version 1.0.3 ?

**Comment by jan-wassenberg** [comment]
Thank you @malaterre for letting us know. An ABI change was unintentional but I believe your result that it has happened.

It seems the problem is that our dummy implementations of the Sorter functions (which only exist for ABI compatibility) are now inlined and thus not exported. #1451 hopefully fixes this. Would you please confirm, or let me know how you generated the symbols file and its diff?
