### ISSUE TITLE
Automatic unrolling, hoisting and reordering for loops

### ISSUE THREAD

**Issue by matthewkolbe** [google/highway#1455]
I have found myself needing to implement a lot of optimizations that compilers struggle with in the presence of intrinsic functions. I shared this example with @jan-wassenberg on hacker news: https://godbolt.org/z/cMafh4Pnv

Since I had to do all of the unrolling, hoisting, reordering and loop cleanup over and over, I created a sort of generalized optimization template to take basic information about the loop, and do a sensible set of optimizations for a lot of x86 chips.  

Below is a basic example using highway. I normally use it on intrinsics, so I just did a quick example in highway. I'll make it more thorough if this is interesting to you all.

https://gcc.godbolt.org/z/9hrrGs6We

The gist is it uses the CRTP with default implementations to provide an `unroller` function the necessary implementation details to optimize the loop. Then you pass the data and an instance of this function to the `unroller` function to run a reasonably well optimized loop for a typical use case. 

My questions: is this interesting? And if so, does it belong in highway? I have found it takes a lot of headache and confusion away when using intrinsics.

**Comment by jan-wassenberg** [comment]
Hi @matthewkolbe , sorry to reply late. That's indeed interesting! It hides much of the difficulty of remainder handling.
We welcome such things in hwy/contrib :)

What you have is more flexible than the hwy/contrib/transform-inl.h, which does take care of masking but currently only manages to 'zip' several arrays and then apply a function to each vector, including remnants.
I like your idea to also support reduction.

For maskload/maskstore, check out transform-inl. Unfortunately we require an `#if` to check whether the platform's masking is even safe (AVX-512 yes, AVX2 no).

Sometimes I've seen better codegen from returning vectors rather than output parameters. Might be good to switch to that.

FYI Highway currently only requires C++11. It would be nice to retain support for that if possible, resorting to `#if` when necessary (see HWY_GENERIC_LAMBDA). Do you think that's feasible?

**Comment by matthewkolbe** [comment]
@jan-wassenberg, it looks like the feature I most depend on is a C++20 feature. In order to have a default "base class" implementation within CRTP, I used the `requires` expression. I'll look into it more, but I'm not sure I can get around that, but if instead we use single-class inheritance, it would be just as performant, right?

For loop cleanup, traditionally, I've had my masking operation fall back to a scalar one if masking wasn't available. Highway doesn't seem to have its function calls "fall back" in this way. This also suffers from the possibility that the scalar implementation doesn't exactly match the SIMD implementation (e.g. see using Agner's `exp` versus `std::exp`). The other two ways are:

- If `n>lanes` and it's not a gather operation, then set `i = n-lanes`, and do a full lane of processing. 
- Otherwise, create `T x_temp[lanes]` on the stack with a suitable default (e.g. for `min`, fill it with max values), fill it partially with the input data, and do a full lane of processing after that. But the scalar load/store element of this is bad.

That last one is pretty slow, but with a large enough `n`, its speed gets diluted away. 

What would be your preference? I only know what works for x86 intrinsics, so your input on how these decisions impact the other architectures would be much appreciated.

> Sometimes I've seen better codegen from returning vectors rather than output parameters.

I agree. I use outparams for the `func` and `reduce_vec` calls so the user can have it accumulate, but I suppose `yy = f.func(i, xx, yy);` can be just as effective. Yeah. That would probably work.

**Comment by matthewkolbe** [comment]
@jan-wassenberg should I take your statement about masked load/store to mean that `hn::MaskedLoad` introduces UB by possibly reading unallocated memory when it's called on older architectures?

**Comment by jan-wassenberg** [comment]
I think single-class inheritance is worth a try :)

On the masking/remainder: does this [doc](https://github.com/google/highway#strip-mining-loops) help?
We can indeed do 'scalar' using CappedTag<T, 1>, and that will actually still use SIMD instructions, but just one at a time and with careful load/stores.

The first option you mention is neat, but that does require that the operation be idempotent/repeatable. How should we have users signal that their function meets that requirement?

The x_temp approach is less attractive on SVE and especially RVV because they can have huge vectors that might exceed some (parsimonious) stack sizes. But those are also the targets with the best (AVX3 is also good) support for masking, so stack storage is anyway avoidable.

It could be reasonable to check !HWY_HAVE_SCALABLE, in which case a stack array is OK. Otherwise (HWY_HAVE_SCALABLE) it's currently the case that HWY_MEM_OPS_MIGHT_FAULT == 0, so we can safely do masked operations. Does that make sense?

**Comment by jan-wassenberg** [comment]
Ah, almost missed your second message :)

Yes, MaskedLoad can be UB if HWY_MEM_OPS_MIGHT_FAULT. This is mainly because AMD's AVX2 reserves the right to fault even if the AVX2 masked load/store have mask=false. (I have not seen them do so, but documentation mentions they might.) Also, we often see msan errors when reading past the valid end of an array, even if the memory is padded (but not initialized). Hence when building with msan, HWY_MEM_OPS_MIGHT_FAULT = 1 regardless of target.

There are some ops `SafeFillN` and `SafeCopyN` which are basically wrappers around MaskedLoad with a check for HWY_MEM_OPS_MIGHT_FAULT, but I'm not sure it's best to rely on those. If HWY_MEM_OPS_MIGHT_FAULT, it might be that there is a better way to do the entire operation which does not involve potentially slow, element-by-element loads. For example, x86_128-inl.h CompressBlendedStore knows that the mask will be contiguous, so instead of checking each lane we can simply memcpy.

Hope that helps?

**Comment by matthewkolbe** [comment]
Single-class inheritance was giving me some troubles. I might revisit later. But I settled on using the CRTP, where the user can shadow a base class implementation. Some of the methods still use outparams because I want them to optionally be no-ops. 

For masking/remainder, I went a slightly different route than the options you presented in that document. If the total size of the processed array is less than the lanes and `HWY_MEM_OPS_MIGHT_FAULT`, then it goes through `x_temp` approach. I don't really see any way around that other than with an alternative scalar processing routine. And hopefully the `HWY_MEM_OPS_MIGHT_FAULT` check prevents RVV from entering that path.

To clean up the remainder, I use masking, but I do it in a way that ensures memory safety even for the unsafe masked load/store ops. First I move the load index back to `n-lanes`, then mask out the lanes that have already been processed. This ensures only allocated memory is in the `MaskedLoad` range.

https://github.com/matthewkolbe/highway/blob/unroller/hwy/contrib/unroller/unroller-inl.h

I haven't made any tests or done formatting or even integrated it into cmake yet. Here is a godbolt example: https://gcc.godbolt.org/z/qnG3Pcd9f

There are still two types of functionality that I would like to handle, and am going to keep working to make them happen. 

(1) Right now, `IN_T` and `OUT_T`  types need to have the same lane sizes, which means it cannot support things like converting from 32-bit types to 64-bit. I'm working to fix that.

(2) I want it to support inputs and outputs that are more than just numeric types. For example, I want it to take in an array of `struct Point { double x; double y; }` types, and to process them as well. This is related to my first goal, because input may be `Point*` and output a `double*` of norms. But this may require some big changes to the interface.

**Comment by matthewkolbe** [comment]
@jan-wassenberg 

I have a perspective on scatter/gather that's forward looking. Since I'm building an unroller in anticipation of needs, I feel like the usefulness of `gather` shouldn't be ignored, and maybe this is the place to talk about it.

I think gather is very underappreciated and underutilized. The obvious use case is in sparse matrix math. But I think it goes a lot deeper than that. Gather allows us to pierce into structured data efficiently, and I don't think people appreciate this yet. So, if you say want to compute the L2 Norm on a list of `Point3D` objects, you can cast them to their base type, and `gather` every `3*i` for the `x`s and `3*i+1` for the `y`s, and so on. With some tooling and support, this process could become much easier, and maybe usher this library out of operating on primitive types alone, which would greatly expand its potential reach.

**Comment by jan-wassenberg** [comment]
Nice progress, it's coming together :) Some comments/suggestions on the code:

For constmin you could use HWY_MIN if you like.

Do you think we should support partial D/tags? It could be someone wants to process half vectors, or max 4 lanes, etc.

How about ptrdiff_t instead of int? Int not matching the native word size sometimes worsens codegen.

Instead of mask = detail::Iota0 (which is an implementation detail) < limit, how about FirstN(d, limit)?
BTW we have Not(FirstN) on the wishlist, tentatively called AfterN unless you have a nicer idea for the name?

Does places < 0 generate a branch? Maybe we can consider Set(places) and then doing branchless SIMD IfThenElse. Or even BroadcastSignBit(Set(d, places)) and using that to negate (2's complement: XOR+SUB).

To make clear that lanes() is constexpr, maybe call it MaxLanes? (We use PascalCase)

Using x_temp if not HWY_MEM_OPS_MIGHT_FAULT seems reasonable/workable. Nice trick with the moved-back MaskedLoad, sounds good.

On gather: sure, great to think ahead. What's the more robust support you mention - is it the mixed lane sizes?
I mainly see Gather as useful for vectorized hash tables. Unfortunately it's rather slow, ballpark one cycle per element. For structured data, if it cannot be given as SoA already, it's probably faster to use Load/StoreInterleaved2. Would that work for the use cases you have in mind?
