### ISSUE TITLE
Remove most GCC/pragma about warnings

### ISSUE THREAD

**Issue by malaterre** [google/highway#1544]
GCC 13 has come a long way and most pragma (-Wuninitialized and al.) can be removed now:

* https://salsa.debian.org/debian-phototools-team/highway/-/blob/debian/experimental/debian/patches/warnings.patch

The only remaining are the implementation specific `Undefined`:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=arm64&ver=1.0.5%7Egit20230630.17ba660-2&stamp=1688315521&raw=0
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=ppc64el&ver=1.0.5%7Egit20230630.17ba660-2&stamp=1688315033&raw=0

So quick question:

* Is there a real interest in having Undefined by an unitialized implementation (Zero is used sometimes) ?
* Or can we use a random generator function (eg. Fill16BytesSecure) to fill in junk values ?

**Comment by jan-wassenberg** [comment]
Interesting, always nice to see compiler progress.
I think we'd still have to keep the pragmas to help with older compilers because those will still be used for some years, right?

Undefined is a very minor optimization. It's reasonable to replace it with zero-init instead, that is actually almost zero-cost on modern CPUs. Do you think we should?

**Comment by jan-wassenberg** [comment]
hm, I think we could actually do:

```
push
#if GCC < 1300
#pragma disable certain warning
#endif
// Uninitialized()
pop
```

I guess your concern is that this is verbose, and there is little advantage to leaving enabled the warning because it anyway only has an effect between push/pop. Agreed :)
