### ISSUE TITLE
std::is_trivial< hwy::N_EMU128::Mask128<double,1> >::value == false

### ISSUE THREAD

**Issue by malaterre** [google/highway#1770]
Long story short I see that 57e1b30 changed EMU128/Vec128 & Mask to non-trivial type. At the same time ebccc445 tried to avoid the 

`warning: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ copying an object of non-trivial type ‘struct hwy::N_EMU128::Vec128<unsigned char, 1>’ from an array of ‘const struct hwy::N_EMU128::Vec128<signed char, 1>’ [-Wclass-memaccess]`

I am wondering, if really this is the right solution. I cannot find the original warning that 57e1b30 triggered...

**Comment by jan-wassenberg** [comment]
Thanks for raising this :) I think the warnings were for msan, it does seem useful that we can have local Vec128 on the stack be default-initialized without writing {} everywhere.

I understand the problem with a ctor, or rather member initialization, is that we cannot memcpy. But we can fix that by changing the memcpy from &vec to &vec.raw, right? It is safe to copy just the member array.

**Comment by jan-wassenberg** [comment]
I agree this would be consistent with other Vec128 classes, but the usage is a bit different here. There are about 5 places where we have a stack vector that is initialized later. Those could be updated, but I'm concerned that partial vector 'initialization' everywhere else would still skip the upper lanes because their loops stop at `N < 16/sizeof(T)`, so we would have uninitialized memory. Thus it is important to initialize everything at construction. Does that make sense?

**Comment by jan-wassenberg** [comment]
That code is intended to work for all targets :)

I appreciate your bug reports and am happy to help keep them warning-free. The above patch fixes all the occurrences of Copy* of the entire vector that I found. Does that solve the problem for you? If not, where is the warning coming from?
