### ISSUE TITLE
Adding support for IBM/Z14 and onwards

### ISSUE THREAD

**Issue by seiko2plus** [google/highway#1895]
### Brief

IBM/Z has introduced SIMD extensions comparable to those in PowerPC64's `VSX`, starting with the IBM/Z13 a.k.a `VX`.
Nonetheless, implementing support for the `Z13` is not applicable, this is because Highway assumes the support of single-precision operations and any blind conversions involving from/to double-precision might lead to decreased performance compared to scalar operations.
Therfore, it is more appropriate to initiate support from the `IBM/Z14` onwards.

### Motivation

Recently, there have been discussions in Numpy advocating for the abandonment of its own SIMD framework(universal intrinsics) and replacing it with Googls's Highway. NumPy provides SIMD support for IBMZ starting from `IBM/Z13`, any future move to Highway will require the support of this architecture.

### References
- [GCC build options](https://gcc.gnu.org/onlinedocs/gcc/S_002f390-and-zSeries-Options.html)
- [NumPy's Implmentation](https://github.com/numpy/numpy/tree/main/numpy/_core/src/common/simd/vec) supports both `VSX` and `VX` under the same path.

**Comment by johnplatts** [comment]
Implementing the HWY_Z13 target requires using the `+`, `-`, `*`, and `/` operators available with GCC/Clang vector extensions instead of the vec_add, vec_sub, vec_mul, and vec_div intrinsics that are available on Altivec/VSX.

The HWY_Z13 target also needs to avoid using the POWER-specific inline assembly that is there in hwy/ops/ppc_vsx.h to work around suboptimal GCC/Clang code generation and GCC/Clang compiler bugs on PPC8/PPC9/PPC10.

The Z13 architecture does support the __vector double type and __vector double arithmetic ops, and a Compiler Explorer snippet that works on both Z13 and POWER7 can be found at https://godbolt.org/z/xWG6MdYcf.

It is also possible to re-implement the PPC8/PPC9/PPC10/WASM targets (and the SSE2/SSSE3/SSE4/AVX2/AVX3/NEON targets when compiled with GCC or Clang) to use GCC/Clang vector extensions for the Load, LoadU, Store, StoreU, Add, Sub, Mul, Div, Set, Dup128VecFromValues, And, AndNot, Or, Xor, Not, BitCast, and ResizeBitCast operations.

It is also possible to re-implement PromoteTo, ConvertTo, and float->float/integer DemoteTo operations to use the __builtin_convertvector intrinsic available on Clang 3.4 and later and GCC 12 and later. Also need to be careful when the GCC/Clang __builtin_convertvector intrinsic is used for float to integer conversions as the __builtin_convertvector intrinsic may have undefined behavior if `v[i] >= LimitsMin<TFromD<DI>>() && v[i] < ((LimitsMax<TFromD<DI>>() / 2) + 1) * TFromV<V>(2)` is not true for any of the source lanes of `v`.

Platform-specific intrinsic-based implementations of the Load/Store, basic arithmetic ops, BitCast/ResizeBitCast, and Set/Dup128VecFromValues would still need to be available on x86/NEON targets to allow Google Highway to be compiled with MSVC.

Re-implementing the PPC8/PPC9/PPC10/WASM targets to use GCC/Clang vector extensions for some of the vector operations would also allow the MSA (MIPS SIMD Architecture) target to be added to Google Highway.

**Comment by jan-wassenberg** [comment]
Thanks @seiko2plus , as mentioned we'd welcome a patch that adds this, and would then support it assuming it works in QEMU.

From what @johnplatts is saying, it sounds like adding `#if` to ppc_vsx would be the fastest way to get there.

GCC 12 is still pretty new, so we will probably want to keep the intrinsic versions of ConvertTo etc for a while.
Do we know someone who would want to use Highway for MSA ?

**Comment by johnplatts** [comment]
> From what @johnplatts is saying, it sounds like adding `#if` to ppc_vsx would be the fastest way to get there.

Also need to add the HWY_Z14, HWY_Z15, and HWY_Z16 targets as Z14 lacks native instructions for F32->UI32 and UI32->F32 vector conversions and as Z16 has native F16->F32 and F32->F16 conversion instructions that are not available on Z14/Z15.

What bits should be used for the HWY_Z14, HWY_Z15, and HWY_Z16 constants in hwy/base.h?

**Comment by jan-wassenberg** [comment]
Sounds good 👍 
Z series and POWER/VSX do not overlap, i.e. are never present on the same machine nor binary, right?
If so, we can split up Z14..16. For example, 14 and 15 could take the currently unused bits 50/51, then we could put Z16 in bit 44, leaving some space for both PPC and Z to grow. How does that sound?

**Comment by seiko2plus** [comment]
Close it as resolved, zSystem has been completely supported by #1906, thank you!
