### ISSUE TITLE
how to convert int8_t vec to int64_t vec?

### ISSUE THREAD

**Issue by esrrhs** [google/highway#2014]
Hi. I want to convert a int8_t vec to int64_t vec, and I read document many times and still can't work.
```
int8_t in[16];
const hwy::HWY_NAMESPACE::ScalableTag<int8_t> d8;
auto vec8 = LoadU(d8, in + i);
auto vec64 = ? 
```
I guess should use **PromoteTo**, but can't compile success.
Thanks.

**Comment by jan-wassenberg** [comment]
Hi, here's how to go about it: we check quick_reference for PromoteTo and notice that "signed to wider signed" covers the types we want.
Then we 'reshape' the tags to a vector of the same size, but the desired i64 lanes:
`const hwy::HWY_NAMESPACE::Repartition<int64_t, decltype(d8)> d64;`.

Now the trick is that PromoteTo expects an input with the same number of lanes as the output, so that would be 1/8th of a full vector, hence `vec64 = PromoteTo(d64, LowerHalf(LowerHalf(LowerHalf(vec8))));`

As a slight shortcut, `auto vec64 = PromoteLowerTo(d64, LowerHalf(LowerHalf(vec8)));` also works. The LowerHalf just make sure the types match, and have no cost.

Hope this helps?

**Comment by esrrhs** [comment]
it works. thank you for your help :)
