### ISSUE TITLE
Support GatherIndex different sizes (_mm512_i64gather_epi32 etc.)

### ISSUE THREAD

**Issue by henrixapp** [google/highway#2023]
Hi,

I am currently using Highway and in particular its GatherIndex method and so far it has been a nice experience.

However, I noticed that for GatherIndex to work, the size of indices and output in bits must match. 
This is unfortunate, since it forces me to use 64bit values for some indices array, that could be 32 bit.

The Intel intrinsics guide [1] tells me that there are instructions to load 32 bit by 64 bit integers on AVX, but I did not find usage in this repository.

Is there a reason in general, why Highway does not support loading 32 bit values  by 64-bit indices?

Or could we add the `*_i64_gather_epi32` functions to the lines around https://github.com/google/highway/blob/2a3ea913f56bb6b7a8b3a71c3c4ded1aa370935b/hwy/ops/x86_512-inl.h#L3377

Thank you for this awesome project!

Henrik

[1] https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_i64gather_epi32&ig_expand=3782,3773,3774,3783,3774

**Comment by jan-wassenberg** [comment]
Thanks for reaching out, glad to hear you had a good experience.

That's right, x86 is the only platform I know of with 32->64 bit gathers. To improve performance portability, we prefer to omit it.

Is it an option for you to PromoteTo the i32 to i64 before GatherIndex? I imagine that would be nearly free assuming port5 is not busy.

**Comment by henrixapp** [comment]
Thanks for the swift response! I can understand that you prefer to omit it.

Closing this for now.

**Comment by hrkalona** [comment]
Well, but if the target does not support gather or scatter, then we are forced to promote to int64 for no reason, and from my experiments I see a performance penalty.

**Comment by jan-wassenberg** [comment]
Acknowledged :) Out of curiosity, how severe is the penalty?
We can weigh that against the cost (to other platforms) of encouraging this pattern which would be more expensive on all other targets except x86.

**Comment by hrkalona** [comment]
Well let me establish the test case. We had our own multi-targeting code and we decided to switch to Highway.
So as part of my benchmarks was to run a test on the following targets: sse2, sse4.2, axv2, avx3).
Our avx2/avx3 implementations were performing similarly to highway.

Here are the times in ms for a specific test using sse2 and sse4.2 which had a large deviation.
Our test included gather and scatter using a 32bit int index. (For highway this must be promoted)

Our sse2 implementation: 154.62 ms
Highway sse2 implementation: 175.6 ms

Our sse4.2 implementation: 153.9 ms
Highway sse4.2 implementation: 159.98 ms

The times were averaged out over many tests. Even if the times seem to be low, they are very important to us.

So when I used the flags HWY_NATIVE_GATHER and HWY_NATIVE_SCATTER in order to create some code that does the the indexing one on a non-vectorized manner and then performs one Load or Store. My temporary array holding the indexed values was aligned.

After this change,
Highway sse2 implementation: 155.3 ms
Highway sse4.2 implementation: 154 ms

In any case higher targets that can perform gather and scatter, will also be affected by having to do a promotion, but this is another topic.

I understand the need to have a consistent API, but it would good if we somehow allowed 32bit index gathers/scatters for 64bit data just for x86.

**Comment by jan-wassenberg** [comment]
Thanks for sharing the data. Sounds like scalar Gather/Scatter is actually better/about as good?
This unfortunately often the case unless nontrivial vector code comes before or after the values loaded/stored, especially since Intel patched the microcode recently.

> if we somehow allowed 32bit index gathers/scatters for 64bit data just for x86.

This is actually possible without any change to Highway. You can define your own wrapper functions that take Highway vectors and call the intrinsics directly, passing v.raw as the argument. The whole thing would be `#if HWY_ARCH_X86`. That way, you get the perf you want and other users (who might not have considered the tradeoffs as carefully) aren't tempted to use the nonportable half-width gather. WDYT?

**Comment by hrkalona** [comment]
Good idea, I was already using a wrapper, so I will just use the intrinsics for avx2, avx3, when my data type is 8 byte and my index type 4 byte.
