### ISSUE TITLE
[feature request] Add a HWY_REGISTER_CALL macro for __vectorcall

### ISSUE THREAD

**Issue by MattiaMontanari** [google/highway#2025]
`__vectorcall` is used in SIMD math libraries to squeeze performance by requesting arguments to be passed as registers rather than on stack. I think this flag applies to MSVS only, but I also think that it would be nice to have it in HWY because:
1. Anyone using HWY uses HWY_RESTRICT and so why not having  HWY_REGISTER_CALL.
2. Highway is amazing in making SIMD more accessible to developers who are not masters in this art - like myself - and `HWY_REGISTER_CALL` will help people's learning in two ways. Firstly by highlighting the fact that passing registers by value is preferred (I don't have the experience to dare saying _better_) than by reference. Secondly by reminding that C++ methods have an hidden input parameter that may deserve some consideration when writing fast SIMD libraries. 

Could be as simple as:
```
#if !defined(HWY_REGISTER_CALL)
	#if defined(_MSC_VER)
		#define HWY_REGISTER_CALL __vectorcall
	#else
		#define HWY_REGISTER_CALL
	#endif
#endif
```

Feel free to close right away is too much of an esoteric feature request :)

**Comment by jan-wassenberg** [comment]
Hi, thanks for raising the issue. For MSVC, I think it makes sense to build with [/Gv](https://learn.microsoft.com/en-us/cpp/build/reference/gd-gr-gv-gz-calling-convention?view=msvc-170) so that (almost) all functions are vectorcall. One disadvantage is that this does not cover member functions.

We could add this REGISTER_CALL but it would not cover a lot of existing code. Conversely, changing HWY_API and perhaps even HWY_INLINE would cover almost all code, but I think that's an ABI break because some users link dynamically, which would break our compatibility promise.

One other consideration is that we usually see better codegen from GCC and especially Clang, thus I'd recommend people switch away from MSVC where possible.

What do you think?

**Comment by MattiaMontanari** [comment]
Thanks for the clear answer. I understand and I agree, I didn't know MSVC had a flag for this and clearly there is no reason to add a new macro a this stage.

Thanks! Awesome work!
