### ISSUE TITLE
`SetTableIndices` for `TableLookupBytes` raises a compilation error on NEON

### ISSUE THREAD

**Issue by Ryo-not-rio** [google/highway#2049]
When performing a table lookup with the `SetTableIndices` instruction the following error is raised:

```
error: no matching function for call to ‘TableLookupBytes(hwy::N_NEON::Vec128<signed char, 8>&, hwy::N_NEON::Indices128<unsigned char, 16>&)’ 
```
It looks like the interface for TableLookupBytes needs to be updated to accept the hwy::N_NEON::Indices128 type.

This can be worked around by creating the indices using `LoadU` for now but this shouldn't be the permanent solution.

**Comment by jan-wassenberg** [comment]
Can you share the source code? I think the issue is that only TableLookup**Lanes** is meant to use the Indices128 returned by IndicesFromVec or SetTableIndices.

For TableLookupBytes, it is fine and in fact intended to pass a normal vector as the second arg.

This is because TableLookup**Lanes** requires some pre-processing of the indices in case the ISA does not support lookups of that lane size, and we have to synthesize them from 8-bit VTBL.

Hope this helps?

**Comment by Ryo-not-rio** [comment]
oh I see, will it be unreasonable to stop supporting `SetTableIndices` for `TableLookupBytes` all together to avoid confusion?

**Comment by jan-wassenberg** [comment]
:) Yes, I think we could do that. I'm not sure on which platform SetTableIndices actually works for TableLookupBytes - is it only SVE? There we struggle because we cannot have wrapper types, so it's hard to prevent.

If however it works on something like x86 or NEON, then yes, we could and should remove that overload. We promise not to break code that follows the documented interface, but it is mentioned that SetTableIndices is for TableLookupLanes, and that TableLookupByte takes a vector argument.

**Comment by Ryo-not-rio** [comment]
We've tried it on SVE and an intel Xeon machine, I'm not sure which instructions it compiles to on that but we've only found SetTableIndices to not work on NEON
