### ISSUE TITLE
Stable `vqsort`

### ISSUE THREAD

**Issue by alantudyk** [google/highway#2284]
Compaction (`Compress` op) is stable (never changes the order of equal keys), with auxiliary memory you (not me) can implement stable sort with separated key and payload.

Does someone know such implementation?

**Comment by jan-wassenberg** [comment]
I agree Compress is stable, but partition is considerably more complex due to handling non-padded arrays: it visits keys in non-sequential order. Also it's not clear to me that the sorting network is stable, so it seems like this would be a bigger undertaking, and I'm not aware of anyone who has done it.
