### ISSUE TITLE
Add support for LoongArch

### ISSUE THREAD

**Issue by XiWeiGu** [google/highway#2386]
LoongArch provides the `cpucfg` instruction to check whether the hardware supports `LSX` and `LASX`, as referenced below:
```
#define LASX_MASK       1<<7
#define LSX_MASK        1<<6
#define LOONGARCH_CFG2  0x02

void get_cpu_lsx_lasx_support(void) {
  int ret = 0;
  __asm__ volatile (
    "cpucfg %0, %1 \n\t"
    : "+&r"(ret)
    : "r"(LOONGARCH_CFG2)
  );

  if (ret & LASX_MASK)
    printf("CPU Support LASX \n");

  if (ret & LSX_MASK)
    printf("CPU Support LSX \n");
}
```
`getauxval` is used to check if the system supports the `LSX` and `LASX` instruction set
```
#include <sys/auxv.h>

#define LA_HWCAP_LSX        (1U << 4)
#define LA_HWCAP_LASX       (1U << 5)

/* Detect whether the OS supports the LSX instruction set */
static int os_support_lsx() {
  int hwcap  = (int)getauxval(AT_HWCAP);

  if (hwcap & LA_HWCAP_LSX)
    return 1;
  else
    return 0;
}

/* Detect whether the OS supports the LASX instruction set */
static int os_support_lasx() {
  int hwcap  = (int)getauxval(AT_HWCAP);

  if (hwcap & LA_HWCAP_LASX)
    return 1;
  else
    return 0;
}
```

**Comment by jan-wassenberg** [comment]
Thanks! Some questions:
Is there a predefined macro like __POWER10_VECTOR__ to indicate that the user wants to enable/assume support for LSX/LASX?
And what is the corresponding `#pragma target`?

What should be the name of the HWY_ARCH_X86 equivalent? HWY_ARCH_LOONG?

**Comment by johnplatts** [comment]
> Thanks! Some questions: Is there a predefined macro like `__POWER10_VECTOR__` to indicate that the user wants to enable/assume support for LSX/LASX? And what is the corresponding `#pragma target`?
> 
> What should be the name of the `HWY_ARCH_X86` equivalent? `HWY_ARCH_LOONG`?

Here are the predefined macros that are defined by GCC or Clang if compiling for the LoongArch target:
- **`__loongarch__`** - defined if compiling on LoongArch32 or LoongArch64, undefined otherwise
- **`__loongarch64`** - defined if compiling on LoongArch64, undefined otherwise

Here are the predefined macros that are defined by GCC or Clang if the LSX/LASX extensions are enabled:
- **`__loongarch_sx`** - defined if LSX extensions are enabled, undefined otherwise
- **`__loongarch_asx`** - defined if LASX extensions are enabled, undefined otherwise

Support for the LSX and LASX intrinsics was added in GCC 14 and Clang 18.

The GCC/Clang __builtin_shufflevector intrinsic is also guaranteed to be available on LSX/LASX targets due to the requirement of GCC 14 or later or Clang 18 or later for the LSX/LASX targets, and the __builtin_shufflevector intrinsic needs to be used to implement some of the ops on the LASX target, including Vec256->Vec128 LowerHalf/UpperHalf and Vec128->Vec256 Combine.

Codegen for Vec256->Vec128 LowerHalf/UpperHalf and Vec128->Vec256 is also suboptimal on LASX with GCC 14, Clang 18, and Clang 19, but the upcoming Clang 20 release under development (which is scheduled to be released in Spring 2025) has much better codegen for Vec256->Vec128 LowerHalf/UpperHalf and Vec128->Vec256 on LASX.

**Comment by jan-wassenberg** [comment]
Thank you @johnplatts ! I'm adding those to detect_targets.h.
Interesting, sounds like you already have experience with LoongArch?

**Comment by XiWeiGu** [comment]
Support for the LoongArch architecture has been completed in  PR #2388 ; closing this issue.

**Comment by jan-wassenberg** [comment]
It's fine to close this, but just to be clear, for anyone else interested: we do not yet have a PR for the actual intrinsics.

**Comment by jinboson** [comment]
> It's fine to close this, but just to be clear, for anyone else interested: we do not yet have a PR for the actual intrinsics.

We will create PR for the actual intrinsics when ready, thanks !
