### ISSUE TITLE
[Arm Neon] Loading/Storing Multiple 128 Bit Vectors At Once

### ISSUE THREAD

**Issue by FabianSchuetze** [google/highway#2393]
Thanks for the wonderful repo and documentation.

Is there the ability to load/store multiple 128-bit vectors with Highway for Neon targets? For example, say, load a value of `int8x16x4_t`. I believe HW's `Tuple<T,N>` types serve as a skeleton for the Arm types, but I don't see a compatible function Load function from the [API](https://google.github.io/highway/en/master/quick_reference.html#load).

If such functionality is unavailable, should I rely on compiler optimization and unroll the loads by factor 4? I see the usage of such types mostly in loads and stores, but other ops then require `.value[N]` specifications.

**Comment by jan-wassenberg** [comment]
:) Glad to hear it is useful.
We indeed currently do not support/target multiple-vector loads such as LD3. This is because they generally do not have much advantage, and sometimes a penalty, vs individual loads. Is there a particular reason you are wanting to target them?

Yes, generally manual unrolling is a good idea, because there are multiple pipelines and instructions have multi-cycle latency, and compilers are often not able to do the unrolling themselves (e.g. due to floating-point non-associativity).

**Comment by johnplatts** [comment]
> Thanks for the wonderful repo and documentation.
> 
> Is there the ability to load/store multiple 128-bit vectors with Highway for Neon targets? For example, say, load a value of `int8x16x4_t`. I believe HW's `Tuple<T,N>` types serve as a skeleton for the Arm types, but I don't see a compatible function Load function from the [API](https://google.github.io/highway/en/master/quick_reference.html#load).
> 
> If such functionality is unavailable, should I rely on compiler optimization and unroll the loads by factor 4? I see the usage of such types mostly in loads and stores, but other ops then require `.value[N]` specifications.

Google Highway has LoadInterleaved2, LoadInterleaved3, and LoadInterleaved4 ops that are wrappers around `vld2[q]_*`, `vld3[q]_*`, and `vld4[q]_*` on NEON targets, but the LoadInterleaved2, LoadInterleaved3, and LoadInterleaved4 ops return the loaded vectors through vector reference arguments instead of returning the loaded vectors in a tuple to remain compatible with RVV (which didn't support scalable vector tuple types with GCC 15 or earlier or GCC 13 or earlier).

Likewise, Google Highway has StoreInterleaved2, StoreInterleaved3, and StoreInterleaved4 ops that are wrappers around `vst2[q]_*`, `vst3[q]_*`, and `vst4[q]_*` ops on NEON targets, but take the additional vectors as separate function arguments instead of passing them through a tuple.

The NEON `vtbl2_*`, `vtbl3_*`, `vtbl4_*`, `vqtbl2q_*`,  `vqtbl3q_*`, and  `vqtbl4q_*` intrinsics take a tuple argument, but the Google Highway TwoTablesLookupLanes op, which is a wrapper around `vtbl1_*`, `vtbl2_*`, `vtbl4_*`, or `vqtbl2q_*` depending on vector size on NEON targets, takes two Google Highway vector arguments.

It is possible to more efficiently implement ThreeTablesLookupLanes and FourTablesLookupLanes on some targets, including NEON (using `vtbl3_*`, `vtbl4_*`, `vqtbl3q_*`, `vqtbl4q_*`), PPC10 (using `vec_permx`), and AVX3 (using `_mm*_mask_permutex2var_*`).

The Armv7 NEON `vzip[q]_*`, `vuzp[q]_*`,  and `vtrn[q]_*` intrinsics return their results in a tuple, but the Google Highway ConcatOdd, ConcatEven, InterleaveLower, InterleaveUpper, InterleaveEven, and InterleaveOdd ops return a single vector.

**Comment by johnplatts** [comment]
NEON has `vld2[q]_lane_*`, `vld3[q]_lane_*`, and `vld4[q]_lane_*` intrinsics, which are equivalent to the following:
```
template <int kLane, class D>
void Interleaved2InsertLane(D d, Vec<D>& v0, Vec<D>& v1,
                            TFromD<D>* HWY_RESTRICT ptr) {
  static_assert(0 <= kLane && kLane < HWY_MAX_LANES_D(D),
                "The lane index must be non-negative and less than or equal to "
                "MaxLanes(d)");
  v0 = InsertLane(v0, static_cast<size_t>(kLane), ptr[0]);
  v1 = InsertLane(v1, static_cast<size_t>(kLane), ptr[1]);
}

template <int kLane, class D>
void Interleaved3InsertLane(D d, Vec<D>& v0, Vec<D>& v1,
                            TFromD<D>* HWY_RESTRICT ptr) {
  static_assert(0 <= kLane && kLane < HWY_MAX_LANES_D(D),
                "The lane index must be non-negative and less than or equal to "
                "MaxLanes(d)");
  v0 = InsertLane(v0, static_cast<size_t>(kLane), ptr[0]);
  v1 = InsertLane(v1, static_cast<size_t>(kLane), ptr[1]);
  v2 = InsertLane(v2, static_cast<size_t>(kLane), ptr[2]);
}

template <int kLane, class D>
void Interleaved4InsertLane(D d, Vec<D>& v0, Vec<D>& v1,
                            TFromD<D>* HWY_RESTRICT ptr) {
  static_assert(0 <= kLane && kLane < HWY_MAX_LANES_D(D),
                "The lane index must be non-negative and less than or equal to "
                "MaxLanes(d)");
  v0 = InsertLane(v0, static_cast<size_t>(kLane), ptr[0]);
  v1 = InsertLane(v1, static_cast<size_t>(kLane), ptr[1]);
  v2 = InsertLane(v2, static_cast<size_t>(kLane), ptr[2]);
  v3 = InsertLane(v3, static_cast<size_t>(kLane), ptr[3]);
}
```

**Comment by FabianSchuetze** [comment]
Thanks for the kind and very interesting replies! 

At first, I should have stated that I was not thinking of interleaved loads/stores but multiple sequential loads and stores. The intrinsics would be (for load) vld1[q]_T_xN (LD1). 

I am interested in multiple loads and stores because of the latency benefits. My programs generally profited from it, but I might confound the effects with unrolling benefits. 

To obtain data, I did benchmark tests on loads and stores with one and four registers and found that using four is generally faster. On an A-76 (old Pixel 6), the difference seems to be 10%. On an X3 (Samsung S9 tablet), the difference is about 20%. I find benchmarking on these devices slightly unreliable because of the CPU and memory frequency scaling, but both results point in the same direction. I think the difference stems from the stores. The difference in latency, however, doesn't seem to conform to the software optimization guides. For the X3 (https://developer.arm.com/documentation/pjdoc466751330-590747/latest/), the load and store latencies seem identical.

ASIMD load, 1 element, multiple, 1 reg, Q-form, LD1: 6 Latency, 3 Throughput
ASIMD load, 1 element, multiple, 4 reg, Q-form, LD1: 7 Latency, 3/4 Throughput
ASIMD store, 1 element, multiple, 1 reg, Q-form, ST1: 2 Latency, 1 Throughput
ASIMD store, 1 element, multiple, 1 reg, Q-form, ST1: 2 Latency, 1/2 Throughput

The benchmark code I used is:
```ASM
.text
.global load
.type load, %function

load:
    ld1 {v0.16b, v1.16b, v2.16b, v3.16b}, [x0], #64
    ld1 {v4.16b, v5.16b, v6.16b, v7.16b}, [x0], #64;
    ld1 {v8.16b, v9.16b, v10.16b, v11.16b}, [x0], #64
    ld1 {v12.16b, v13.16b, v14.16b, v15.16b}, [x0]
    st1     { v0.16b, v1.16b, v2.16b, v3.16b }, [x1], #64
    st1     { v4.16b, v5.16b, v6.16b, v7.16b }, [x1], #64
    st1     { v8.16b, v9.16b, v10.16b, v11.16b }, [x1], #64
    st1     { v12.16b, v13.16b, v14.16b, v15.16b }, [x1]
    ret

.global load_individually
.type load_individually, %function
load_individually:
    ld1 {v0.16b}, [x0], #16
    ld1 {v1.16b}, [x0], #16
    ld1 {v2.16b}, [x0], #16
    ld1 {v3.16b}, [x0], #16
    ld1 {v4.16b}, [x0], #16
    ld1 {v5.16b}, [x0], #16
    ld1 {v6.16b}, [x0], #16
    ld1 {v7.16b}, [x0], #16
    ld1 {v8.16b}, [x0], #16
    ld1 {v9.16b}, [x0], #16
    ld1 {v10.16b}, [x0], #16
    ld1 {v11.16b}, [x0], #16
    ld1 {v12.16b}, [x0], #16
    ld1 {v13.16b}, [x0], #16
    ld1 {v14.16b}, [x0], #16
    ld1 {v15.16b}, [x0]
    st1 {v0.16b}, [x1], #16
    st1 {v1.16b}, [x1], #16
    st1 {v2.16b}, [x1], #16
    st1 {v3.16b}, [x1], #16
    st1 {v4.16b}, [x1], #16
    st1 {v5.16b}, [x1], #16
    st1 {v6.16b}, [x1], #16
    st1 {v7.16b}, [x1], #16
    st1 {v8.16b}, [x1], #16
    st1 {v9.16b}, [x1], #16
    st1 {v10.16b}, [x1], #16
    st1 {v11.16b}, [x1], #16
    st1 {v12.16b}, [x1], #16
    st1 {v13.16b}, [x1], #16
    st1 {v14.16b}, [x1], #16
    st1 {v15.16b}, [x1]
    ret                       ;
```

and 
```c++
#include <arm_neon.h>  // for vaddq_u8, uint8x16_t, vqtbl2q_u8
#include <benchmark/benchmark.h>

#include <algorithm>  // for min
#include <cstdint>    // for uint8_t
#include <iostream>
#include <numeric>
#include <random>
#include <vector>  // for vector

using vec_uint8 = uint8x16x4_t;

extern "C" vec_uint8 load(const uint8_t* ptr, uint8_t* out);
extern "C" vec_uint8 load_individually(const uint8_t* ptr, uint8_t* out);

//void print_vector(uint8_t* out) {
    //printf("\n");
    //for (size_t i = 0; i < 16 * 4 * 4 * 4 * 2; ++i) {
        //if (i % 64 == 0) {
            //printf("\n%zu: ", i);
        //}
        //printf("%hhu", out[i]);
        //printf(", ");
    //}
//}
int pin_thread(int core_id, int tid) {
    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(core_id, &cpuset);
    int rc = sched_setaffinity(tid, sizeof(cpu_set_t), &cpuset);
    return rc;
}

template <auto F, size_t N>
void __attribute__((noinline)) loop(const uint8_t* ptr, uint8_t* out) {
    constexpr size_t stepsize{16 * 4 * 4};
    for (size_t i = 0; i < N;
         i += 4 * stepsize, ptr += 4 * stepsize, out += 4 * stepsize) {
        F(ptr, out);
        F(ptr + stepsize, out + stepsize);
        F(ptr + 2 * stepsize, out + 2 * stepsize);
        F(ptr + 3 * stepsize, out + 3 * stepsize);
    }
}

void fill_vector(std::vector<uint8_t>& vec) {
    std::random_device rnd_device;
    // Specify the engine and distribution.
    std::mt19937 mersenne_engine{rnd_device()};  // Generates random integers
    std::uniform_int_distribution<uint8_t> dist{0, 255};
    auto gen = [&]() { return dist(mersenne_engine); };
    std::generate(vec.begin(), vec.end(), gen);
}

template <auto F>
static void BM(benchmark::State& state) {
    pin_thread(7, gettid()); // strongest core in tablet/phone
    constexpr size_t stepsize{16 * 4 * 4 * 4};
    constexpr size_t N{stepsize * 100};
    std::vector<uint8_t> input(N), output(N, 0);
    fill_vector(input);
    uint8_t* inputp = input.data();
    uint8_t* outputp = output.data();
    for (auto _ : state) {
        loop<F, N>(inputp, outputp);
        benchmark::DoNotOptimize(outputp);
        benchmark::DoNotOptimize(inputp);
    }
    //print_vector(outputp);
    //print_vector(inputp);
    float res = std::accumulate(inputp, inputp + N, 0.0f);
    float res2 = std::accumulate(outputp, outputp + N, 0.0f);
    std::cout << "Sanity check: Sum Input: " << res << ", Sum Output: " << res2
              << std::endl;
}
// Register the function as a benchmark
BENCHMARK(BM<load_individually>);
BENCHMARK(BM<load>);
// Run the benchmark
BENCHMARK_MAIN();
```

**Comment by jan-wassenberg** [comment]
Are you sure latency is the driver here? Usually you want to unroll enough that the latency is hidden, and throughput is more interesting.

Do you actually have a std::transform-like use case where you also want to store data, or load-only like dot product? The best approaches may differ because Arm has pipelines that either load or store.

Looking at the X3 guide, the throughput for LD4 is one every two cycles, whereas you should be able to do 3x128-bit loads per cycle.
Perhaps there is some other bottleneck. I'm not very familiar with Arm assembly, isn't that an auto-increment form? Quite possible it cannot handle multiple of those per cycle from the same base reg.

**Comment by FabianSchuetze** [comment]
Thanks for the detailed and interesting comment. I take the your point of throughput being more interesting the latency. I do have a transform like usecase but I'll post it in a new issue for conciseness once I've implemented it with HW. I close this issue. Thanks again for the great answers!
