### ISSUE TITLE
numpy CI failed on loongarch qemu test

### ISSUE THREAD

**Issue by jinboson** [google/highway#2410]
Hi, @jan-wassenberg . 
Numpy CI failed on loongarch qemu test, here is the PR link :　https://github.com/numpy/numpy/pull/27856.
The error link is : https://github.com/numpy/numpy/actions/runs/12312221518/job/34363842899?pr=27856.
I haven't figured out the problem. Is that because we haven't added instrinsics support into highway after we added LSX/LASX targets?

**Comment by jan-wassenberg** [comment]
Yes, those errors are because generic_ops-inl.h expects the intrinsics file to define many things such as VFromD, but because it's an empty header, that does not happen.
We cannot actually compile the HWY_LSX target until it is actually implemented. However, you could define HWY_COMPILE_ONLY_SCALAR and then it should at least build, though it would only use scalar (non-SIMD) code.

**Comment by jinboson** [comment]
Sorry for the delay reply.   @jan-wassenberg Thank you so much, that works.  Sorry, it will take some time to add intrinsics into highway for LSX/LASX targets, so is it possible to pre-define the HWY_COMPILE_ONLY_SCALAR to help numpy build successfully ? And then when the intrinsics are added we will remove the HWY_COMPILE_ONLY_SCALAR immediately. If possible, where you prefer to define the HWY_COMPILE_ONLY_SCALAR ? It's availabe on numpy side or must be on highway side ? Thanks.

**Comment by jinboson** [comment]
We think this can be closed now, thank you @jan-wassenberg .
