### ISSUE TITLE
highway/hwy/base.h:343:19: error: ‘__fp16’ does not name a type

### ISSUE THREAD

**Issue by malaterre** [google/highway#467]
Currently JPEG-XL fails to build on riscv64 with the following error:

```
In file included from /<<PKGBUILDDIR>>/third_party/highway/hwy/contrib/image/image.h:28,
                 from /<<PKGBUILDDIR>>/third_party/highway/hwy/contrib/image/image.cc:15:
/<<PKGBUILDDIR>>/third_party/highway/hwy/base.h:343:19: error: ‘__fp16’ does not name a type
  343 | using float16_t = __fp16;
      |                   ^~~~~~
/<<PKGBUILDDIR>>/third_party/highway/hwy/base.h:546:18: error: ‘float16_t’ was not declared in this scope; did you mean ‘float64_t’?
  546 | struct Relations<float16_t> {
      |                  ^~~~~~~~~
      |                  float64_t
```

Starring at the GCC online documentation, I must say I do not understand where this __fp16 is coming from ?

* https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html

Could someone please document the source code for C-compiler requirement (eg. is clang required on linux/riscv64) ?

reference:
* https://buildd.debian.org/status/fetch.php?pkg=jpeg-xl&arch=riscv64&ver=0.6.1%2Bds-5&stamp=1639586263&raw=0

**Comment by jan-wassenberg** [comment]
Hi @malaterre, thanks for reaching out.
The GCC and clang headers for RISC-V have been changing. The latter currently use __fp16 pointer args, now gated by a __riscv_zfh macro.

Highway's handling of this has also changed. Here's the current code I see referenced by JPEG XL:

```
#if HWY_ARCH_ARM && (__ARM_FP & 2)
#define HWY_NATIVE_FLOAT16 1
#else
#define HWY_NATIVE_FLOAT16 0
#endif
...
#elif HWY_NATIVE_FLOAT16
using float16_t = __fp16;
```

Thus I think __fp16 would not be used - could it be that updating the submodules fixes this?

Unfortunately, when I last checked, GCC didn't yet support the new RVV intrinsics with extra avl argument, do you know if that has changed? Highway requires that new form of intrinsics.

There may be additional changes required in JPEG XL because some of its code predates the RVV requirements. I'm happy to help advise on that and will return from holidays on Dec20.

**Comment by malaterre** [comment]
OK, I understand now. I've prepared an upload for highway (*), so that I can reduce the coupling of jpeg-xl version to a particular highway version in the future. I'll close the issue for now, we'll see how it goes. Thanks.

(*) https://ftp-master.debian.org/new/highway_0.15.0-1.html

**Comment by jan-wassenberg** [comment]
@malaterre Ah, great, thanks! Sounds good.
