### ISSUE TITLE
Using Interleave* is impossible because of missing definition in N_SCALAR

### ISSUE THREAD

**Issue by amyspark** [google/highway#590]
Hi!

I'm researching if we can migrate our app to Highway. I found that currently it's not possible to build our test benchmark with Highway, because the Interleave functions aren't defined for the N_SCALAR target.

Godbolt: https://gcc.godbolt.org/z/3GoKds893

**Comment by yzazik** [comment]
Well, if I may, N_SCALAR actually has functionality of 1_SCALAR (a _vector_ with one scalar only), so only things that _make sense_ are implemented.

I guess, interleaving two scalars (two 1_SCALARs) to result in one (1_SCALAR) would mean either keeping one or another or somehow make a mix of _half scalar_ of each into one.

In other words, since it is not as straightforward as for example wit 2_SCALARs, the decision is left to a user to implement one suitable for the task.

I think, the talk about implementing N_SCALAR as N_SCALAR (ie vector with N scalars) has started (not explicitly though) in #264, no work force has been assigned to do it, neither the real world benefit in assembly or performance has been observed (if that matters in this case). So I would guess, people probably keep their original non-HWY scalar code as is in '#if HWY_TARGET == HWY_SCALAR' of some sort.

**Comment by jan-wassenberg** [comment]
Hi @amyspark and @yzazik, that's right, it doesn't seem possible to implement Interleave for HWY_SCALAR.
We do have the closely related `ZipLower` op for exactly this reason: it's the same thing but returns a double-wide type, so interleaving 1x8 and 1x8 = 1x16 bits as expected. But there is no `ZipUpper` because what's the upper half of a one-vector?

Can you help me understand why we need N_SCALAR at all? Highway only requires S-SSE3 on x86, which is quite old and widely supported. The simplest fix would be to tell the compiler that we always have that: add -mssse3 compiler option.

It's true that we'd like to support an 'EMU128' target which would be 16/sizeof(T) lanes, but work hasn't started and there's no ETA. Would be happy to help with or collaborate on that, though.

**Comment by amyspark** [comment]
> Can you help me understand why we need N_SCALAR at all?

Indeed it's not possible to implement the scalar version. However, this was a direct use of Highway, following its quick reference, on one of its examples.

What we use at work is a custom dispatch routine e.g. `if current_arch() == HWY_SSSE3 return function1(); else...`, so we have a specific, non-Highway implementation for that case. But since Highway requires the macro (afaik) `HWY_DYNAMIC_DISPATCH` to do the dispatching, I am left unable to handle the scalar case.

**Comment by amyspark** [comment]
@jan-wassenberg Here's the current Vc implementation for the dynamic dispatch: https://github.com/KDE/krita/blob/9374dd18790017c0216982595ce2a5a498c7c477/libs/pigment/compositeops/KoVcMultiArchBuildSupport.h

**Comment by amyspark** [comment]
> The latter option seems better, would that work for you?

@jan-wassenberg I'll check it out and let you know, thanks 😄

**Comment by jan-wassenberg** [comment]
Hi @amyspark, FYI an EMU128 target that supports all ops and guarantees 128-bit vectors is now implemented (#634), pending review. I believe this would also fix the issue you encountered?

**Comment by amyspark** [comment]
Definitely, thanks @jan-wassenberg !
