### ISSUE TITLE
understanding the type of gather/scatter indices

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#639]
From the documentation and a bit of tentative coding, I get the impression that in order to use highway's gather/scatter with memory of type T, the gather/scatter indices need to be vectors of a signed integer type with the same number of bits. The documentation also doesn't mention use of short or byte types as T.
Is that really so? To gather doubles, I have to use int64_t indices? I'd rather have a choice - e.g. gather doubles with int32_t indices - like with __m256d _mm256_i32gather_pd.

**Comment by jan-wassenberg** [comment]
That's right, same size but signed and non-negative - this is because RISC-V differs from other platforms in treating indices as unsigned.

8/16 bit types indeed aren't supported because some hardware (in this case x86) doesn't.

AFAIK x86 is in turn the only platform that lets us gather f64 using i32. Would it be an option to PromoteTo(di64, your_int32_vec)?

**Comment by kfjahnke** [comment]
With my [new template class](https://github.com/google/highway/issues/641) I can use goading for the purpose. This does usually work quite well - simple loops like the 'rolled-out' gather/scatter operation are quite easy to be recognized as amenable to autovectorization. I can dispatch internally, looking at the sizes of the data and indices, and if they agree I'll route to hwy code, and to goading otherwise. I'd rather avoid having to hand-code index type promotions, but if that produces a speedup it may be worth the effort. Thank you for your explanation - I mainly asked the question to make sure I hadn't missed something!
