### ISSUE TITLE
0.17.0 build issue with MSVC

### ISSUE THREAD

**Issue by jobbautista9** [google/highway#811]
We're trying to build your library for Pale Moon's platform, but it fails to build `contrib/image/image.cc` on MSVC 2015 for Windows, which is likely caused by `<std*.h>` and `<cstddef>` includes on both the `.cc` and `.h` files. Logs of the error can be found at https://repo.palemoon.org/attachments/ed92e227-a483-47e6-a29d-ebf9e9e5ed05 and https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1928#issuecomment-31217. The pull request for highway's inclusion is at https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1928. Highway's refusal to build is literally the only blocker preventing us from getting JPEG-XL support into our browser.

Pinging @wolfbeast who is the one who found this issue.

**Comment by jobbautista9** [comment]
Tag libjxl/libjxl#1525

**Comment by jan-wassenberg** [comment]
Thanks for reaching out @jobbautista9 . The quickest way to work around this issue would be to run CMake with `-DHWY_ENABLE_CONTRIB=OFF`. JPEG XL does not require files in this directory.

Note that MSVC 2015 is very old, and although we have been able to keep alive a build pipeline for it, and support it until now, you'll definitely want the latest available patch for it (Update 3). That one is [>40 releases old by now](https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd); better still would be something considerably newer such as 2019, because MSVC has had numerous bugs relating to SFINAE ([example](https://developercommunity.visualstudio.com/t/problem-with-stdenable-if-in-vc1911255082/118023)).

Are either of those an option for you?

**Comment by jobbautista9** [comment]
We use the latest available patch for MSVC 2015; it's a prerequisite for [building Pale Moon on Windows](http://developer.palemoon.org/build/windows/). I don't think MSVC 2019 is an option for us, but I will let @wolfbeast clarify that.

We don't use CMake for our build system I think, but I will look into disabling building Highway on Windows (it can remain in GNU/Linux, SunOS, and macOS, which builds fine there). I thought Highway was required due to how libjxl's [`convolve.cc`](https://xref.palemoon.org/mozilla-central/source/third_party/jpeg-xl/lib/jxl/convolve.cc) used it a lot for example.

**Comment by jan-wassenberg** [comment]
That's right, it is not possible to remove Highway entirely. I was thinking we could avoid building the files in hwy/contrib (including the image.cc mentioned in the build log) - those are not used by JPEG XL.

**Comment by jan-wassenberg** [comment]
Clarification also posted to https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1928: I was mistaken in thinking our CI/CD runs MSVC 2015 - it’s actually at MSC_VER=1928 (2019). So that one is known to work.

We might be able to make it work for MSVC_VER=1910 (MSVC 2017), but earlier versions are probably not going to fly due to difficult to work around SFINAE bugs in those compilers.

We do have some knobs to help deal with broken compilers: it will likely help to build with `-DHWY_BROKEN_TARGETS=(HWY_AVX2|HWY_AVX3|HWY_AVX3_DL)`.

**Comment by wolfbeast** [comment]
> I don't think MSVC 2019 is an option for us, but I will let @wolfbeast clarify that.

It's been one of the things that has been constantly pushed back, Among other things due to the constant pressure a now no longer present team member was putting on us. Our code base is however quite obscenely large (and we've been trying to diet it where we can, but still...) as well as relying on some pretty old code in critical paths that isn't fully understood in its entirety by anyone who is actively involved, so changing compiler is a big task especially since there are breaking changes -- it's akin to touching every line of code. I'm sure that 2017 can be done but 2019 might need a lot more changes.

We should be able to use our build system to pass in defines as a workaround or simply exclude the contrib directory if you know it's not needed for JPEG XL.

**Comment by jan-wassenberg** [comment]
@jobbautista9 
After commits f7bd7dc0069046c896aa65e43ecbc5aa2362637d and 4fa872a2a0d9944cb5fe761669ac63096607d3a3 I believe Highway is ready for MSVC 2017. Please reopen if you still see issues :)
