### ISSUE TITLE
How to remove tail loop with SVE

### ISSUE THREAD

**Issue by cyb70289** [google/highway#820]
Hi,

With SVE we can eliminate the tail loop (handling data fewer than vector size) with predicates.
I'm wondering if `highway` supports it. If it's possible, how can the code be compatible with other ISA.

Below is a simple example doing vertical add to calculate `z[i] = x[i] + y[i]`.

**intrinsics, no tail loop**
```
void sum_sve(const int* x, const int* y, size_t size, int* z) {
  for (size_t i = 0; i < size; i += svlen(svint32_t()) {
    const svbool_t pred = svwhilelt_b32(i, size);
    const svint32_t vx = svld1(pred, x + i);
    const svint32_t vy = svld1(pred, y + i);
    const svint32_t vz = svadd_z(pred, vx, vy);
    svst1(pred, z + i, vz);
  }
}
```

**highway, with tail loop**
```
void sum_hwy(const int* x, const int* y, size_t size, int* z) {
  const ScalableTag<int> d;
  size_t i = 0;
  for (; i + Lanes(d) <= size; i += Lanes(d)) {
    auto vx = Load(d, x + i);
    auto vy = Load(d, y + i);
    auto vz = Add(vx, vy);
    Store(vz, d, z + i);
  }
  // tail loop to process remaining data
  for (; i < size; ++i) {
      z[i] = x[i] + y[i];
  }
}
```

**Comment by jan-wassenberg** [comment]
Hi @cyb70289 , yes, this is indeed possible :) The first observation is that most operations can be done without predicates - it's fine to compute svadd for extra elements, but would not be fine to store them, or count them (CNTP). Thus only a few operations require a predicate. In this case, you can use MaskedLoad and BlendedStore instead of Load/Store, and FirstN to generate the predicate (equivalent of WHILELO).

Although this is portable, it can be more expensive on other platforms that don't have native predicates. What we recommend is to have a non-predicated main loop, and then one final iteration using predicates.

The [readme mentions some other options](https://github.com/google/highway#strip-mining-loops). Hope this helps?

**Comment by cyb70289** [comment]
Thanks @jan-wassenberg for the explanation! It makes sense.
