### ISSUE TITLE
Implement runtime dispatch on riscv64

### ISSUE THREAD

**Issue by malaterre** [google/highway#838]
This is a ticket to track progress on runtime dispatch for riscv64 (followup to issue #818).

For now, unit tests are failing, see Debian/riscv64 buildd:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=0.17.1%7Egit20220707.b0108ff-1&stamp=1657192132&raw=0

**Comment by malaterre** [comment]
This may take a bit of back-n-forth as Debian does not offer riscv64 porterbox:

* https://wiki.debian.org/RISC-V#Porterboxes

So I kindly requested on debian-riscv mailing list to do it for me:

* https://lists.debian.org/debian-riscv/2022/07/msg00020.html

will update the progress here.

**Comment by jan-wassenberg** [comment]
Sounds good, thanks!

**Comment by malaterre** [comment]
I was granted access to the following hardware (*), it seems that the instructions is not supported:

```
$ ctest -R TestAllMulHigh/RVV -V
[...]
147: Note: Google Test filter = HwyMulTestGroup/HwyMulTest.TestAllMulHigh/RVV
147: [==========] Running 1 test from 1 test suite.
147: [----------] Global test environment set-up.
147: [----------] 1 test from HwyMulTestGroup/HwyMulTest
147: [ RUN      ] HwyMulTestGroup/HwyMulTest.TestAllMulHigh/RVV
1/1 Test #147: HwyMulTestGroup/HwyMulTest.TestAllMulHigh/RVV  # GetParam() = 268435456 ...***Exception: Illegal  0.13 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.18 sec

The following tests FAILED:
	147 - HwyMulTestGroup/HwyMulTest.TestAllMulHigh/RVV  # GetParam() = 268435456 (ILLEGAL)
Errors while running CTest
Output from these tests are in: /home/malaterre/highway-0.17.1~git20220711.f0a396a/obj-riscv64-linux-gnu/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

(*)
```
$ cat /proc/cpuinfo 
processor	: 0
hart		: 2
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 1
hart		: 1
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 2
hart		: 3
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 3
hart		: 4
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0
```

**Comment by jan-wassenberg** [comment]
That's right, we'd have to see v in the list of isa extensions. I see mention of Sifive bullet from 2020, whereas the V spec was ratified only a few months ago. We're testing using Spike or QEMU.

**Comment by malaterre** [comment]
Just for reference, current debian patch is:

* https://salsa.debian.org/debian-phototools-team/highway/-/blob/debian/0.17.1_git20220711.f0a396a-1/debian/patches/riscv.patch

**Comment by jan-wassenberg** [comment]
Nice, I think the bit we want to test is 1 << ('v' - 'a').

**Comment by malaterre** [comment]
> 1 << ('v' - 'a')

Lower-case ? Anyway I'll integrate the patch as-is in next upload.

**Comment by malaterre** [comment]
@jan-wassenberg could you comment on my patch see above. it seems I am missing something:

[...]
[28/103] /usr/bin/clang++-14 -DHWY_SHARED_DEFINE -Dhwy_contrib_EXPORTS -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety-analysis -Wundefined-func-template -fno-cxx-exceptions -fno-slp-vectorize -fno-vectorize -fdiagnostics-show-option -fcolor-diagnostics -Wc++2a-extensions -fmath-errno -fno-exceptions -march=rv64gcv1p0 -menable-experimental-extensions -MD -MT CMakeFiles/hwy_contrib.dir/hwy/contrib/image/image.cc.o -MF CMakeFiles/hwy_contrib.dir/hwy/contrib/image/image.cc.o.d -o CMakeFiles/hwy_contrib.dir/hwy/contrib/image/image.cc.o -c '/<<PKGBUILDDIR>>/hwy/contrib/image/image.cc'
[...]

thje above seems to puts v-extensions in shared logic.

**Comment by jan-wassenberg** [comment]
Yes indeed, you could also write 'V' - 'A' (it is the same).

For the patch, we want to also do what was done for Arm ([commit](https://github.com/google/highway/commit/d8867c95df5c5bcd33562b3a24c96f5a54d298a8)). This is a bit harder to see because the patch also included other required fixes, but the key parts we haven't yet added are:

1) In detect_targets.h:405
`#define HWY_ATTAINABLE_TARGETS` should also be done if `ARCH_RVV` in addition to `ARCH_ARM`.

2) In set_macros-inl.h we want to `#define HWY_TARGET_STR` to whatever the compiler requires. This is usually xx if the compiler flag were -mxx, but on RVV we previously used -march=rv64gcv1p0 so I'm not sure what the syntax is.

Actually I see in the LLVM headers that RVV currently has the same issue as NEON/SVE: they do not yet support runtime dispatch. An [issue has been filed](https://github.com/llvm/llvm-project/issues/56480) and discussions are ongoing at least for Arm.

It's possible that GCC already supports this for RVV like they do for NEON/SVE. If so, you would see in its riscv_vector.h some target attribute in the function definitions, and that is what we want to define HWY_TARGET_STR to.

**Comment by malaterre** [comment]
> It's possible that GCC already supports this for RVV like they do for NEON/SVE. If so, you would see in its riscv_vector.h some target attribute in the function definitions, and that is what we want to define HWY_TARGET_STR to.

I cannot find a file `riscv_vector.h` in my gcc-12 install tree:

* https://packages.debian.org/sid/riscv64/libgcc-12-dev/filelist

clang seems to offer it:

* https://packages.debian.org/sid/riscv64/libclang-common-14-dev/filelist

But as you guessed the include file is messed up:

```
% head -20 /usr/lib/llvm-14/lib/clang/14.0.6/include/riscv_vector.h | tail -5

#ifndef __riscv_vector
#error "Vector intrinsics require the vector extension."
#endif
```

**Comment by malaterre** [comment]
For reference:

* https://github.com/llvm/llvm-project/issues/56592

**Comment by jan-wassenberg** [comment]
For HWY_TARGET_STR, this [comment](https://github.com/llvm/llvm-project/issues/56480#issuecomment-1190271810) suggests that arch=rv64gcv1p0 might be exactly what we want.

**Comment by malaterre** [comment]
Current WIP in Debian is at:

* https://salsa.debian.org/debian-phototools-team/highway/-/blob/debian/experimental/debian/patches/riscv.patch

**Comment by malaterre** [comment]
Current gcc status:

* https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1106#issuecomment-1233901350

See:

 * https://github.com/riscv-collab/riscv-gcc/blob/riscv-gcc-rvv-next/gcc/config/riscv/riscv-vector.h

**Comment by malaterre** [comment]
`rdcycle` is currently producing SIGILL on Debian env, so no progress on riscv64 for me until issue is solved:

* https://lists.debian.org/debian-riscv/2022/08/msg00049.html

**Comment by jan-wassenberg** [comment]
Thanks for making us aware. This situation is regrettable: an important feature (cycle counter or even timer) has been demoted from the base spec (where it was when I last checked) to an extension, which is not yet ratified. I fail to see how it makes sense to ship a board without something as basic as a timer (nor how this was considered 'optional' in the spec), but both seem to have happened.

We will disable it for now and fall back to `clock_gettime`.

**Comment by malaterre** [comment]
> an important feature (cycle counter or even timer) has been demoted from the base spec (where it was when I last checked) to an extension

wait, what ? SIGILL is produced on the same actual physical board. I fail to understand why an instruction would suddenly fail to execute depending on the running linux kernel.

**Comment by jan-wassenberg** [comment]
Are we sure about it being the same board? I saw this in the Debian discussion:

> - Hifive Unleashed running a 5.10.28 kernel
> - Polarfire Icicle running kernel 5.18.14-1
> However it produces a SIGILL on
> - Hifive Unmatched running a 5.18.14-1 kernel
> - Hifive Unmatched running a 5.18.16-1 kernel

**Comment by malaterre** [comment]
> Are we sure about it being the same board?

mailing list archive are hard to read from one month to the other :(

Here is my post from this morning:

* https://lists.debian.org/debian-riscv/2022/09/msg00000.html

If you want the full summary, I also posted here:

* https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/REWcwYnzsKE/m/gdKCQn-dBwAJ

Repeated here for clarity:

> It works fine on
> - QEMU running a 5.18.16-1 kernel
> - Hifive Unleashed running a 5.10.28 kernel
> - Hifive Unmatched running a 5.16.14-1 kernel
> - Polarfire Icicle running kernel 5.18.14-1
> 
> However it produces a SIGILL on
> - Hifive Unmatched running a 5.18.14-1 kernel
> - Hifive Unmatched running a 5.18.16-1 kernel

**Comment by jrtc27** [comment]
> Thanks for making us aware. This situation is regrettable: an important feature (cycle counter or even timer) has been demoted from the base spec (where it was when I last checked) to an extension, which is not yet ratified. I fail to see how it makes sense to ship a board without something as basic as a timer (nor how this was considered 'optional' in the spec), but both seem to have happened.
> 
> We will disable it for now and fall back to `clock_gettime`.

Yes, moving things out of the base spec since 2.0 has created a mess, but this is not the issue. The issue is the Linux kernel deliberately disables access to the cycle counter in userspace since 5.18. It does permit access to the timer in userspace. Pre-5.18 the relevant configuration was left untouched so the cycle counter was enabled, but 5.18 landed a commit (https://github.com/torvalds/linux/commit/e9991434596f5373dfd75857b445eb92a9253c56) that added a perf driver, with the side-effect of blocking everything but the timer in userspace (even instret is disabled...), which should still work.

Also note checking for `__riscv_zicntr` isn't that good an idea; if you use an older toolchain, or any version of Clang, that doesn't exist because it's treated as part of RV64I, not because it thinks you shouldn't use the counters... (and they wouldn't accept -march=..._zicntr either).

**Comment by malaterre** [comment]
For reference:

> The breakage happened because the new pmu driver only enabled TM bit by default instead of all three.
> The change was intentional due to security reasons. One rogue process can have access to cycle &
> instructions of the entire kernel always which can lead to some sort of side channel attacks. 
>  
> However, I agree that we can't break userspace. I was not aware of the fact that there are already users of rdcycle
> in the userspace. I will send a patch to restore the original behavior by enabling CY, IR bits in scounteren."
> 

* https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/REWcwYnzsKE/m/Lq7G6jXSBwAJ

**Comment by malaterre** [comment]
For reference:

* https://github.com/google/highway/pull/961

**Comment by jan-wassenberg** [comment]
Thanks @malaterre for CCing me on the email, and thanks @jrtc27 for clearing up my misunderstanding. (The fact that Zicntr is an extension looks like a more theoretical problem, then.)

Let's discuss via email. @jrtc27 , would you also like to join that discussion?

**Comment by malaterre** [comment]
> For the AT_* values, I simply extrapolated from the fact that RISC-V extensions are (or were mostly) identified with a one-letter name, and the convention seems to be a dense bit array in alphabetical order.

Seems like this is still not merged upstream:

* https://www.spinics.net/lists/kernel/msg4354764.html

**Comment by jan-wassenberg** [comment]
An update here for the record, related work ongoing in #1017.
@malaterre has updated our timer to use rdtime instead of rdcycle, though apparently newer Linux will once again allow rdcycle.

Do we want to integrate your patch already to allow runtime dispatch on riscv64 + clang?

**Comment by malaterre** [comment]
@jan-wassenberg there is no-point in trying to merge any of my code for runtime dispatch on riscv64, see above:

* https://github.com/google/highway/issues/838#issuecomment-1238243830

we need to have getauxval (ideally) or at least minimal kernel support from user-space. So far only kernel mode can query the hardware support.

**Comment by jan-wassenberg** [comment]
Do I understand correctly that the issue is that we do have `getauxval`, but not the bit definitions macro for the V extension?

If so, it seems that the patch would remain correct in future when a macro is added, if we used `1 << ('V' - 'A')` which is what the macro will almost certainly evaluate to? I see `COMPAT_HWCAP_ISA_V` is starting to be introduced. Is that what we should be checking for?

Separately, #1017 mentioned that applying your patch helped them get further. It seems that the patch is only adding something for clang, whereas they are using GCC, except for the targets.cc change which causes them to not set the `HWY_RVV` bit.

Something seems to be off about the way they disable V, but still: detecting V support at runtime would indeed help fix their problem, and the patch doesn't hurt in any way, right?

**Comment by davidlt** [comment]
Vector support is not merged yet in Linux or/and glibc for upstream.

Note there aren't enough bits for RISC-V in AT_HWCAP and AT_HWCAP2. There are discussions how to approach HW probing interface for the user space. The latest one is here: https://patchwork.kernel.org/project/linux-riscv/cover/20221013163551.6775-1-palmer@rivosinc.com/

I would advice not to merge a code using COMPAT_HWCAP_ISA_V until that is becomes available in a stable kernel. At that point it's pretty much guaranteed not to change.

In the future (hopefully sooner than later) RISC-V will have it's own syscall or something to allow probing for the details.

**Comment by jan-wassenberg** [comment]
Interesting, that's very recent, thanks for the link. OK, I'm fine to wait on this patch/feature.

In the meantime, as mentioned I think the only difference the patch could be making for you is that in targets.cc it avoids `bits |= HWY_RVV;`. Without the patch it would do `bits |= HWY_ENABLED_BASELINE;` which anyway should be a no-op because you're setting `-DHWY_DISABLED_TARGETS=HWY_RVV` and `__riscv_vector` is hopefully not defined. 

Either of those two should be sufficient for V to be disabled, so not sure what's happening here. Is your `-DHWY_DISABLED_TARGETS=HWY_RVV` being passed to all translation units, both Highway and the user?

**Comment by jan-wassenberg** [comment]
Another idea. What do you think of detecting (lack of) V using a SIGILL handler?

**Comment by malaterre** [comment]
> What do you think of detecting (lack of) V using a SIGILL handler?

Do you know how to do that ? Here is what I read: `man sigaction`:

> According to POSIX, the behavior of a process is undefined after it ignores a SIGFPE, SIGILL, or SIGSEGV signal that was not generated by kill(2) or raise(3).

**Comment by jan-wassenberg** [comment]
Here is a good looking example: https://github.com/randombit/botan/blob/master/src/lib/utils/os_utils.cpp#L694

I believe we are not ignoring the signal (SIG_IGN), nor are we restarting the offending instruction, because we'd siglongjmp out of trouble. Does that seem reasonable?

**Comment by malaterre** [comment]
> Here is a good looking example: https://github.com/randombit/botan/blob/master/src/lib/utils/os_utils.cpp#L694

Looks pretty impressive indeed ! So that would solve the first issue, the remaining one is that highway + RVV imply compiling *all* the sources code with the `rv64gcv1p0` flag (cmake setting is done on a project basis instead, whereas it should be set using selected `pragma` on certain source file).

**Comment by jan-wassenberg** [comment]
:) Right. I've commented on and subscribed to the issue you filed about that, fingers crossed it will happen soon. Once it does, we can do the SIGILL and then runtime dispatch is ready to go.

**Comment by jan-wassenberg** [comment]
Hooray, this is at long last done :D
