### ISSUE TITLE
foreach_target.h:50:18: warning: integer overflow in preprocessor expression

### ISSUE THREAD

**Issue by malaterre** [google/highway#886]
hwy 1.0 is producing a flood of warnings which makes reading log of compilation hard to read. Would it be possible to include a fix for (and others):

```
/<<PKGBUILDDIR>>/hwy/detect_targets.h:453:6: warning: integer overflow in preprocessor expression
/<<PKGBUILDDIR>>/hwy/foreach_target.h:50:18: warning: integer overflow in preprocessor expression
   50 | #if !HWY_IDE && (HWY_TARGETS != HWY_STATIC_TARGET)
      |                  ^~~~~~~~~~~
```

See full log at:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=i386&ver=1.0.0-1&stamp=1659387467&raw=0

**Comment by jan-wassenberg** [comment]
Interesting, this can only happen if `HWY_SCALAR` is used, which was only meant to happen if `HWY_COMPILE_ONLY_SCALAR` (which avoids overflow), but here it's being used because of `HWY_BROKEN_EMU128`. 

Fortunately we can fix the warning without any behavior change. `(HWY_STATIC_TARGET << 1) - 1` is the same as `(HWY_STATIC_TARGET - 1) | HWY_STATIC_TARGET`, switching to that, thanks!
