### ISSUE TITLE
How can I quickly process a JSON array?

### ISSUE THREAD

**Issue by meftunca** [google/highway#963]
The structure that I have developed with primitive methods at the moment provides a speed of 1 GB / s and I want to increase it to higher speeds like simdjson. So I need to do string processing with parallel operations. How might 'highway' work for JSON strings?

**Comment by jan-wassenberg** [comment]
Hi @meftunca , simdjson has its own minimal abstraction layer (see its include/*/simd.h) which calls intrinsics directly. You could replace those intrinsics with calls to Highway ops, for example by searching for the corresponding intrinsic used in our ops/x86_512-inl.h.
One issue is that simdjson relies on a CompressStore for 8-bit lanes. We do not have an implementation of this yet (because it's only efficient on Icelake and later), but it's on our wishlist.

Hope this helps?

**Comment by jan-wassenberg** [comment]
Closing, please feel free to reopen if you have other questions or inputs.
